CREATE MULTISET TABLE [DQ_DATADB_TEMPLATE].DQ_Alert
     (
      sessionid INTEGER,
      DbName VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      TableName VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      ColumnName VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      ToleranceLevel CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('H','L','M'),
      ToleranceVal FLOAT,
      DataType CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC,
      AlertType VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      AlertDetail VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( DbName ,TableName ,ColumnName )
PARTITION BY sessionid ;
