CREATE MULTISET TABLE [DQ_DATADB_TEMPLATE].DQ_Alert_setting
     (
      AlertType VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      ToleranceLevel CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      ToleranceVal FLOAT)
UNIQUE PRIMARY INDEX ( AlertType ,ToleranceLevel );
