CREATE MULTISET TABLE [DQ_DATADB_TEMPLATE].DQ_char_hist
     (
      sessionid BIGINT,
      databasename VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      tablename VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      colname VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      Token VARCHAR(31000) CHARACTER SET UNICODE NOT CASESPECIFIC,
      prv_char_cnt BIGINT,
      new_char_cnt BIGINT)
PRIMARY INDEX ( databasename ,tablename ,colname )
PARTITION BY sessionid ;
