CREATE MULTISET TABLE [DQ_DATADB_TEMPLATE].DQ_control_tbls
     (
      DatabaseName VARCHAR(300) CHARACTER SET LATIN NOT CASESPECIFIC,
      TableName VARCHAR(300) CHARACTER SET LATIN NOT CASESPECIFIC,
      ColumnName VARCHAR(300) CHARACTER SET LATIN NOT CASESPECIFIC,
      ToleranceLevel CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC DEFAULT 'M',
      TsColumn VARCHAR(300) CHARACTER SET LATIN NOT CASESPECIFIC,
      InactiveTSColumn VARCHAR(300) CHARACTER SET LATIN NOT CASESPECIFIC,
      ActiveInd BYTEINT
     )
PRIMARY INDEX ( DatabaseName ,TableName );