CREATE MULTISET TABLE [DQ_DATADB_TEMPLATE].DQ_CAT_PrePostfix
     (
      PrePost VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      Pre_ind BYTEINT,
      Category_ind BYTEINT)
UNIQUE PRIMARY INDEX ( PrePost );
