CREATE MULTISET TABLE [DQ_DATADB_TEMPLATE].DQ_hist_psi
     (
      sessionid BIGINT,
      databasename VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      tablename VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      xcol VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      columntype VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      psi DECIMAL(12,7))
PRIMARY INDEX ( databasename ,tablename ,xcol )
PARTITION BY sessionid ;
