CREATE MULTISET TABLE [DQ_DATADB_TEMPLATE].DQ_process_columns
     (
      sessionid BIGINT,
      DbName VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      TableName VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      ColumnName VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      ToleranceLevel CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('H','L','M'),
      Org_Type VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      Mod_Type VARCHAR(1024) CHARACTER SET LATIN NOT CASESPECIFIC,
      Process_Ts TIMESTAMP(6),
      prv_cnt BIGINT,
      new_cnt BIGINT,
      Proc_Ind CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('N','Y','I'))
PRIMARY INDEX ( DbName ,TableName ,ColumnName )
PARTITION BY sessionid ;
