create database TRNG_RefineryOptimizer from demonow as perm=0;
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_BLEND",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-BLEND/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_BLEND_PRED",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-BLEND-PRED/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_BLEND_RECIPE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-BLEND-RECIPE/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_CALDATE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-CALDATE/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_CONTAINER",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-CONTAINER/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_COST",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-COST/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_COSTFORENSICS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-COSTFORENSICS/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_EXPAND_DAYS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-EXPAND-DAYS/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_EXPAND_SECONDS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-EXPAND-SECONDS/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_EXPAND_YEARS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-EXPAND-YEARS/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_INVENTORY",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-INVENTORY/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_INVENTORY_DCD",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-INVENTORY-DCD/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_LAB",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-LAB/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_LAB_COMP",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-LAB-COMP/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_LAB_COMP_GROUP",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-LAB-COMP-GROUP/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_LIFTINGS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-LIFTINGS/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_MARKETPRICE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-MARKETPRICE/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_MATERIAL",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-MATERIAL/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_MATERIAL_HIER",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-MATERIAL-HIER/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_MATERIAL_HIER_GROU",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-MATERIAL-HIER-GROU/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_MOVEMENTS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-MOVEMENTS/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_OPTTHRUPUT_WEIGHTS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-OPTTHRUPUT-WEIGHTS/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_PRICE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-PRICE/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_PRICE_PLATTS_DCD",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-PRICE-PLATTS-DCD/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_SAFETY",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-SAFETY/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_SENSOR",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-SENSOR/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_SENSOR_DESCUNITS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-SENSOR-DESCUNITS/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_SENSOR_LOADPARAMS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-SENSOR-LOADPARAMS/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_TAG_CONTAINER_XREF",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-TAG-CONTAINER-XREF/'));
create foreign table gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_UNIT",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RefineryOptimizer/DB250092-RO-UNIT/'));
replace view TRNG_RefineryOptimizer.DB250092_RO_BLEND as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_BLEND";
replace view TRNG_RefineryOptimizer.DB250092_RO_BLEND_PRED as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_BLEND_PRED";
replace view TRNG_RefineryOptimizer.DB250092_RO_BLEND_RECIPE as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_BLEND_RECIPE";
replace view TRNG_RefineryOptimizer.DB250092_RO_CALDATE as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_CALDATE";
replace view TRNG_RefineryOptimizer.DB250092_RO_CONTAINER as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_CONTAINER";
replace view TRNG_RefineryOptimizer.DB250092_RO_COST as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_COST";
replace view TRNG_RefineryOptimizer.DB250092_RO_COSTFORENSICS as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_COSTFORENSICS";
replace view TRNG_RefineryOptimizer.DB250092_RO_EXPAND_DAYS as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_EXPAND_DAYS";
replace view TRNG_RefineryOptimizer.DB250092_RO_EXPAND_SECONDS as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_EXPAND_SECONDS";
replace view TRNG_RefineryOptimizer.DB250092_RO_EXPAND_YEARS as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_EXPAND_YEARS";
replace view TRNG_RefineryOptimizer.DB250092_RO_INVENTORY as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_INVENTORY";
replace view TRNG_RefineryOptimizer.DB250092_RO_INVENTORY_DCD as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_INVENTORY_DCD";
replace view TRNG_RefineryOptimizer.DB250092_RO_LAB as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_LAB";
replace view TRNG_RefineryOptimizer.DB250092_RO_LAB_COMP as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_LAB_COMP";
replace view TRNG_RefineryOptimizer.DB250092_RO_LAB_COMP_GROUP as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_LAB_COMP_GROUP";
replace view TRNG_RefineryOptimizer.DB250092_RO_LIFTINGS as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_LIFTINGS";
replace view TRNG_RefineryOptimizer.DB250092_RO_MARKETPRICE as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_MARKETPRICE";
replace view TRNG_RefineryOptimizer.DB250092_RO_MATERIAL as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_MATERIAL";
replace view TRNG_RefineryOptimizer.DB250092_RO_MATERIAL_HIER as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_MATERIAL_HIER";
replace view TRNG_RefineryOptimizer.DB250092_RO_MATERIAL_HIER_GROU as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_MATERIAL_HIER_GROU";
replace view TRNG_RefineryOptimizer.DB250092_RO_MOVEMENTS as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_MOVEMENTS";
replace view TRNG_RefineryOptimizer.DB250092_RO_OPTTHRUPUT_WEIGHTS as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_OPTTHRUPUT_WEIGHTS";
replace view TRNG_RefineryOptimizer.DB250092_RO_PRICE as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_PRICE";
replace view TRNG_RefineryOptimizer.DB250092_RO_PRICE_PLATTS_DCD as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_PRICE_PLATTS_DCD";
replace view TRNG_RefineryOptimizer.DB250092_RO_SAFETY as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_SAFETY";
replace view TRNG_RefineryOptimizer.DB250092_RO_SENSOR as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_SENSOR";
replace view TRNG_RefineryOptimizer.DB250092_RO_SENSOR_DESCUNITS as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_SENSOR_DESCUNITS";
replace view TRNG_RefineryOptimizer.DB250092_RO_SENSOR_LOADPARAMS as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_SENSOR_LOADPARAMS";
replace view TRNG_RefineryOptimizer.DB250092_RO_TAG_CONTAINER_XREF as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_TAG_CONTAINER_XREF";
replace view TRNG_RefineryOptimizer.DB250092_RO_UNIT as locking row for access select * from  gs_tables_db."TRNG_RefineryOptimizer_DB250092_RO_UNIT";
