create database TRNG_EquipFailure from demonow as perm=0;
create foreign table gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_EVENTS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-EquipFailure/DEMO-EQUIP-EVENTS/'));
create foreign table gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_LOGS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-EquipFailure/DEMO-EQUIP-LOGS/'));
create foreign table gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_LOGS_text_output",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-EquipFailure/DEMO-EQUIP-LOGS-text-output/'));
create foreign table gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TESTING",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-EquipFailure/DEMO-EQUIP-TESTING/'));
create foreign table gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-EquipFailure/DEMO-EQUIP-TRAINING/'));
create foreign table gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_acc_output",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-EquipFailure/DEMO-EQUIP-TRAINING-acc-output/'));
create foreign table gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_cluster",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-EquipFailure/DEMO-EQUIP-TRAINING-cluster/'));
create foreign table gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_count_outp",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-EquipFailure/DEMO-EQUIP-TRAINING-count-outp/'));
create foreign table gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_model",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-EquipFailure/DEMO-EQUIP-TRAINING-model/'));
create foreign table gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_model_pred",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-EquipFailure/DEMO-EQUIP-TRAINING-model-pred/'));
create foreign table gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_monitor",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-EquipFailure/DEMO-EQUIP-TRAINING-monitor/'));
create foreign table gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_stat_outpu",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-EquipFailure/DEMO-EQUIP-TRAINING-stat-outpu/'));
create foreign table gs_tables_db."TRNG_EquipFailure_movie_tweets_text_output",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-EquipFailure/movie-tweets-text-output/'));
replace view TRNG_EquipFailure.DEMO_EQUIP_EVENTS as locking row for access select * from  gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_EVENTS";
replace view TRNG_EquipFailure.DEMO_EQUIP_LOGS as locking row for access select * from  gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_LOGS";
replace view TRNG_EquipFailure.DEMO_EQUIP_LOGS_text_output as locking row for access select * from  gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_LOGS_text_output";
replace view TRNG_EquipFailure.DEMO_EQUIP_TESTING as locking row for access select * from  gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TESTING";
replace view TRNG_EquipFailure.DEMO_EQUIP_TRAINING as locking row for access select * from  gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING";
replace view TRNG_EquipFailure.DEMO_EQUIP_TRAINING_acc_output as locking row for access select * from  gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_acc_output";
replace view TRNG_EquipFailure.DEMO_EQUIP_TRAINING_cluster as locking row for access select * from  gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_cluster";
replace view TRNG_EquipFailure.DEMO_EQUIP_TRAINING_count_outp as locking row for access select * from  gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_count_outp";
replace view TRNG_EquipFailure.DEMO_EQUIP_TRAINING_model as locking row for access select * from  gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_model";
replace view TRNG_EquipFailure.DEMO_EQUIP_TRAINING_model_pred as locking row for access select * from  gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_model_pred";
replace view TRNG_EquipFailure.DEMO_EQUIP_TRAINING_monitor as locking row for access select * from  gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_monitor";
replace view TRNG_EquipFailure.DEMO_EQUIP_TRAINING_stat_outpu as locking row for access select * from  gs_tables_db."TRNG_EquipFailure_DEMO_EQUIP_TRAINING_stat_outpu";
replace view TRNG_EquipFailure.movie_tweets_text_output as locking row for access select * from  gs_tables_db."TRNG_EquipFailure_movie_tweets_text_output";
