create database TRNG_BYOM from demonow as perm=0;
create foreign table gs_tables_db."TRNG_BYOM_��_��",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/��-��/'));
create foreign table gs_tables_db."TRNG_BYOM_boston",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/boston/'));
create foreign table gs_tables_db."TRNG_BYOM_energy",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/energy/'));
create foreign table gs_tables_db."TRNG_BYOM_energy_no_consumption_datamart",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/energy-no-consumption-datamart/'));
create foreign table gs_tables_db."TRNG_BYOM_h2o_bad_lic",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/h2o-bad-lic/'));
create foreign table gs_tables_db."TRNG_BYOM_h2o_empty_lic",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/h2o-empty-lic/'));
create foreign table gs_tables_db."TRNG_BYOM_h2o_encypt_lic",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/h2o-encypt-lic/'));
create foreign table gs_tables_db."TRNG_BYOM_h2o_lic",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/h2o-lic/'));
create foreign table gs_tables_db."TRNG_BYOM_h2o_NULL_lic",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/h2o-NULL-lic/'));
create foreign table gs_tables_db."TRNG_BYOM_h2o_spclChar_lic",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/h2o-spclChar-lic/'));
create foreign table gs_tables_db."TRNG_BYOM_housing_test",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/housing-test/'));
create foreign table gs_tables_db."TRNG_BYOM_mojo_models",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/mojo-models/'));
create foreign table gs_tables_db."TRNG_BYOM_mojo_models_7482%$&^%%^ )00",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/mojo-models-7482%$&^%%^ )00/'));
create foreign table gs_tables_db."TRNG_BYOM_mojo_models_dai",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/mojo-models-dai/'));
create foreign table gs_tables_db."TRNG_BYOM_mojo_models_dai222247326472364",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/mojo-models-dai222247326472364/'));
create foreign table gs_tables_db."TRNG_BYOM_mojo_models_noRow",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/mojo-models-noRow/'));
create foreign table gs_tables_db."TRNG_BYOM_mojo_models_opensource",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/mojo-models-opensource/'));
create foreign table gs_tables_db."TRNG_BYOM_mojo_models_opensource26472364",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/mojo-models-opensource26472364/'));
create foreign table gs_tables_db."TRNG_BYOM_mojo_model_dai",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/mojo-model-dai/'));
create foreign table gs_tables_db."TRNG_BYOM_mojo_model_opensource",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/mojo-model-opensource/'));
create foreign table gs_tables_db."TRNG_BYOM_pmml_models",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/pmml-models/'));
create foreign table gs_tables_db."TRNG_BYOM_pmml_models_utf",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/pmml-models-utf/'));
create foreign table gs_tables_db."TRNG_BYOM_results_upload_from_Editor",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/results-upload-from-Editor/'));
create foreign table gs_tables_db."TRNG_BYOM_svm_iris",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/svm-iris/'));
create foreign table gs_tables_db."TRNG_BYOM_svm_iris_new",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/svm-iris-new/'));
create foreign table gs_tables_db."TRNG_BYOM_winesTest",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/winesTest/'));
create foreign table gs_tables_db."TRNG_BYOM_winesTest1",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/winesTest1/'));
create foreign table gs_tables_db."TRNG_BYOM_winesTest2",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/winesTest2/'));
create foreign table gs_tables_db."TRNG_BYOM_winesTest_2",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/winesTest-2/'));
create foreign table gs_tables_db."TRNG_BYOM_winesTest_col",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/winesTest-col/'));
create foreign table gs_tables_db."TRNG_BYOM_winesTest_noRow",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/winesTest-noRow/'));
create foreign table gs_tables_db."TRNG_BYOM_winesTest_small_1",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/winesTest-small-1/'));
create foreign table gs_tables_db."TRNG_BYOM_winesTest_stress4",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/winesTest-stress4/'));
create foreign table gs_tables_db."TRNG_BYOM_wine__&**$_p 0123",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-BYOM/wine--&**$-p 0123/'));
replace view TRNG_BYOM.��_�� as locking row for access select * from  gs_tables_db."TRNG_BYOM_��_��";
replace view TRNG_BYOM.boston as locking row for access select * from  gs_tables_db."TRNG_BYOM_boston";
replace view TRNG_BYOM.energy as locking row for access select * from  gs_tables_db."TRNG_BYOM_energy";
replace view TRNG_BYOM.energy_no_consumption_datamart as locking row for access select * from  gs_tables_db."TRNG_BYOM_energy_no_consumption_datamart";
replace view TRNG_BYOM.h2o_NULL_lic as locking row for access select * from  gs_tables_db."TRNG_BYOM_h2o_NULL_lic";
replace view TRNG_BYOM.h2o_bad_lic as locking row for access select * from  gs_tables_db."TRNG_BYOM_h2o_bad_lic";
replace view TRNG_BYOM.h2o_empty_lic as locking row for access select * from  gs_tables_db."TRNG_BYOM_h2o_empty_lic";
replace view TRNG_BYOM.h2o_encypt_lic as locking row for access select * from  gs_tables_db."TRNG_BYOM_h2o_encypt_lic";
replace view TRNG_BYOM.h2o_lic as locking row for access select * from  gs_tables_db."TRNG_BYOM_h2o_lic";
replace view TRNG_BYOM.h2o_spclChar_lic as locking row for access select * from  gs_tables_db."TRNG_BYOM_h2o_spclChar_lic";
replace view TRNG_BYOM.housing_test as locking row for access select * from  gs_tables_db."TRNG_BYOM_housing_test";
replace view TRNG_BYOM.mojo_model_dai as locking row for access select * from  gs_tables_db."TRNG_BYOM_mojo_model_dai";
replace view TRNG_BYOM.mojo_model_opensource as locking row for access select * from  gs_tables_db."TRNG_BYOM_mojo_model_opensource";
replace view TRNG_BYOM.mojo_models as locking row for access select * from  gs_tables_db."TRNG_BYOM_mojo_models";
replace view TRNG_BYOM.mojo_models_7482%$&^%%^ )00 as locking row for access select * from  gs_tables_db."TRNG_BYOM_mojo_models_7482%$&^%%^ )00";
replace view TRNG_BYOM.mojo_models_dai as locking row for access select * from  gs_tables_db."TRNG_BYOM_mojo_models_dai";
replace view TRNG_BYOM.mojo_models_dai222247326472364 as locking row for access select * from  gs_tables_db."TRNG_BYOM_mojo_models_dai222247326472364";
replace view TRNG_BYOM.mojo_models_noRow as locking row for access select * from  gs_tables_db."TRNG_BYOM_mojo_models_noRow";
replace view TRNG_BYOM.mojo_models_opensource as locking row for access select * from  gs_tables_db."TRNG_BYOM_mojo_models_opensource";
replace view TRNG_BYOM.mojo_models_opensource26472364 as locking row for access select * from  gs_tables_db."TRNG_BYOM_mojo_models_opensource26472364";
replace view TRNG_BYOM.pmml_models as locking row for access select * from  gs_tables_db."TRNG_BYOM_pmml_models";
replace view TRNG_BYOM.pmml_models_utf as locking row for access select * from  gs_tables_db."TRNG_BYOM_pmml_models_utf";
replace view TRNG_BYOM.results_upload_from_Editor as locking row for access select * from  gs_tables_db."TRNG_BYOM_results_upload_from_Editor";
replace view TRNG_BYOM.svm_iris as locking row for access select * from  gs_tables_db."TRNG_BYOM_svm_iris";
replace view TRNG_BYOM.svm_iris_new as locking row for access select * from  gs_tables_db."TRNG_BYOM_svm_iris_new";
replace view TRNG_BYOM.wine__&**$_p 0123 as locking row for access select * from  gs_tables_db."TRNG_BYOM_wine__&**$_p 0123";
replace view TRNG_BYOM.winesTest as locking row for access select * from  gs_tables_db."TRNG_BYOM_winesTest";
replace view TRNG_BYOM.winesTest1 as locking row for access select * from  gs_tables_db."TRNG_BYOM_winesTest1";
replace view TRNG_BYOM.winesTest2 as locking row for access select * from  gs_tables_db."TRNG_BYOM_winesTest2";
replace view TRNG_BYOM.winesTest_2 as locking row for access select * from  gs_tables_db."TRNG_BYOM_winesTest_2";
replace view TRNG_BYOM.winesTest_col as locking row for access select * from  gs_tables_db."TRNG_BYOM_winesTest_col";
replace view TRNG_BYOM.winesTest_noRow as locking row for access select * from  gs_tables_db."TRNG_BYOM_winesTest_noRow";
replace view TRNG_BYOM.winesTest_small_1 as locking row for access select * from  gs_tables_db."TRNG_BYOM_winesTest_small_1";
replace view TRNG_BYOM.winesTest_stress4 as locking row for access select * from  gs_tables_db."TRNG_BYOM_winesTest_stress4";
