create database TRNG_RETAILDSE from demonow as perm=0;
create database TRNG_RETAILDSE_DEV from demonow as perm=0;
grant select on TRNG_RETAILDSE_DEV to public with grant option;
create foreign table gs_tables_db."TRNG_RETAILDSE_ATTRIBUTION_CONVERSION",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/ATTRIBUTION-CONVERSION/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_ATTRIBUTION_MODEL_EXPONENTIAL",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/ATTRIBUTION-MODEL-EXPONENTIAL/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_ATTRIBUTION_MODEL_FIRST_CLICK",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/ATTRIBUTION-MODEL-FIRST-CLICK/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_ATTRIBUTION_MODEL_LAST_CLICK",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/ATTRIBUTION-MODEL-LAST-CLICK/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_ATTRIBUTION_MODEL_UNIFORM",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/ATTRIBUTION-MODEL-UNIFORM/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_CALL_CENTER_CALLS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/CALL-CENTER-CALLS/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_CUSTOMER",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/CUSTOMER/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_PROSPECT",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/PROSPECT/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_PROSPECT_TRANSACTION",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/PROSPECT-TRANSACTION/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_PURCHASE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/PURCHASE/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_RETAIL_COMPNEW",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/RETAIL-COMPNEW/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_SERVER",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/SERVER/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_STORE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/STORE/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_STORE_VISIT",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/STORE-VISIT/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_WEB",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/WEB/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_WEB_COMMENT",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/WEB-COMMENT/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_WEB_CUSTOMER",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/WEB-CUSTOMER/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_WEB_LOG",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/WEB-LOG/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_WEB_LOG_JSON_ONLY",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE/WEB-LOG-JSON-ONLY/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_ASSOC_10PURCHASES",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/ASSOC-10PURCHASES/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_CUSTOMER_MASTER_ATTRIBUTES",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/CUSTOMER-MASTER-ATTRIBUTES/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_CUSTOMER_PURCHASES_FLAT",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/CUSTOMER-PURCHASES-FLAT/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_CUST_CC_EVENTS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/CUST-CC-EVENTS/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_CUST_ONLINE_EVENTS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/CUST-ONLINE-EVENTS/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_CUST_STORE_EVENTS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/CUST-STORE-EVENTS/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_DecisionTreeScore1",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/DecisionTreeScore1/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_DecisionTreeScore1_rpt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/DecisionTreeScore1-rpt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_FactorAnalysisScore1",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/FactorAnalysisScore1/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_FactorAnalysisScore1_rpt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/FactorAnalysisScore1-rpt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_LogisticOut1_rpt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/LogisticOut1-rpt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_LogisticOut1_txt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/LogisticOut1-txt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_LogisticScore1_txt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/LogisticScore1-txt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_LREGModel1_rpt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/LREGModel1-rpt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_LREGModel1_txt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/LREGModel1-txt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_NEW_CUSTOMERS_MASTER",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/NEW-CUSTOMERS-MASTER/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_NEW_RETAIL_ALLCH_EVENT_DESC_MA",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/NEW-RETAIL-ALLCH-EVENT-DESC-MA/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_NEW_RETAIL_CUST_EVENTS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/NEW-RETAIL-CUST-EVENTS/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_TEMP_ERASE_CUSTOMERS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/TEMP-ERASE-CUSTOMERS/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreFrequency",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/TwmExploreFrequency/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreHistogram",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/TwmExploreHistogram/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreStatistics",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/TwmExploreStatistics/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreValues",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/TwmExploreValues/'));
replace view TRNG_RETAILDSE.ATTRIBUTION_CONVERSION as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_ATTRIBUTION_CONVERSION";
replace view TRNG_RETAILDSE.ATTRIBUTION_MODEL_EXPONENTIAL as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_ATTRIBUTION_MODEL_EXPONENTIAL";
replace view TRNG_RETAILDSE.ATTRIBUTION_MODEL_FIRST_CLICK as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_ATTRIBUTION_MODEL_FIRST_CLICK";
replace view TRNG_RETAILDSE.ATTRIBUTION_MODEL_LAST_CLICK as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_ATTRIBUTION_MODEL_LAST_CLICK";
replace view TRNG_RETAILDSE.ATTRIBUTION_MODEL_UNIFORM as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_ATTRIBUTION_MODEL_UNIFORM";
replace view TRNG_RETAILDSE.CALL_CENTER_CALLS as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_CALL_CENTER_CALLS";
replace view TRNG_RETAILDSE.CUSTOMER as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_CUSTOMER";
replace view TRNG_RETAILDSE.PROSPECT as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_PROSPECT";
replace view TRNG_RETAILDSE.PROSPECT_TRANSACTION as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_PROSPECT_TRANSACTION";
replace view TRNG_RETAILDSE.PURCHASE as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_PURCHASE";
replace view TRNG_RETAILDSE.RETAIL_COMPNEW as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_RETAIL_COMPNEW";
replace view TRNG_RETAILDSE.SERVER as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_SERVER";
replace view TRNG_RETAILDSE.STORE as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_STORE";
replace view TRNG_RETAILDSE.STORE_VISIT as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_STORE_VISIT";
replace view TRNG_RETAILDSE.WEB as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_WEB";
replace view TRNG_RETAILDSE.WEB_COMMENT as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_WEB_COMMENT";
replace view TRNG_RETAILDSE.WEB_CUSTOMER as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_WEB_CUSTOMER";
replace view TRNG_RETAILDSE.WEB_LOG as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_WEB_LOG";
replace view TRNG_RETAILDSE.WEB_LOG_JSON_ONLY as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_WEB_LOG_JSON_ONLY";
replace view TRNG_RETAILDSE_DEV.ASSOC_10PURCHASES as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_ASSOC_10PURCHASES";
replace view TRNG_RETAILDSE_DEV.CUSTOMER_MASTER_ATTRIBUTES as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_CUSTOMER_MASTER_ATTRIBUTES";
replace view TRNG_RETAILDSE_DEV.CUSTOMER_PURCHASES_FLAT as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_CUSTOMER_PURCHASES_FLAT";
replace view TRNG_RETAILDSE_DEV.CUST_CC_EVENTS as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_CUST_CC_EVENTS";
replace view TRNG_RETAILDSE_DEV.CUST_ONLINE_EVENTS as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_CUST_ONLINE_EVENTS";
replace view TRNG_RETAILDSE_DEV.CUST_STORE_EVENTS as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_CUST_STORE_EVENTS";
replace view TRNG_RETAILDSE_DEV.DecisionTreeScore1 as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_DecisionTreeScore1";
replace view TRNG_RETAILDSE_DEV.DecisionTreeScore1_rpt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_DecisionTreeScore1_rpt";
replace view TRNG_RETAILDSE_DEV.FactorAnalysisScore1 as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_FactorAnalysisScore1";
replace view TRNG_RETAILDSE_DEV.FactorAnalysisScore1_rpt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_FactorAnalysisScore1_rpt";
replace view TRNG_RETAILDSE_DEV.LREGModel1_rpt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_LREGModel1_rpt";
replace view TRNG_RETAILDSE_DEV.LREGModel1_txt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_LREGModel1_txt";
replace view TRNG_RETAILDSE_DEV.LogisticOut1_rpt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_LogisticOut1_rpt";
replace view TRNG_RETAILDSE_DEV.LogisticOut1_txt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_LogisticOut1_txt";
replace view TRNG_RETAILDSE_DEV.LogisticScore1_txt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_LogisticScore1_txt";
replace view TRNG_RETAILDSE_DEV.NEW_CUSTOMERS_MASTER as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_NEW_CUSTOMERS_MASTER";
replace view TRNG_RETAILDSE_DEV.NEW_RETAIL_ALLCH_EVENT_DESC_MA as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_NEW_RETAIL_ALLCH_EVENT_DESC_MA";
replace view TRNG_RETAILDSE_DEV.NEW_RETAIL_CUST_EVENTS as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_NEW_RETAIL_CUST_EVENTS";
replace view TRNG_RETAILDSE_DEV.TEMP_ERASE_CUSTOMERS as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_TEMP_ERASE_CUSTOMERS";
replace view TRNG_RETAILDSE_DEV.TwmExploreFrequency as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreFrequency";
replace view TRNG_RETAILDSE_DEV.TwmExploreHistogram as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreHistogram";
replace view TRNG_RETAILDSE_DEV.TwmExploreStatistics as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreStatistics";
replace view TRNG_RETAILDSE_DEV.TwmExploreValues as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreValues";
