create database TRNG_Covid360 from demonow as perm=0;
create foreign table gs_tables_db."TRNG_Covid360_ADS_age_factor",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/ADS-age-factor/'));
create foreign table gs_tables_db."TRNG_Covid360_ADS_scenarios",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/ADS-scenarios/'));
create foreign table gs_tables_db."TRNG_Covid360_ADS_Simulation",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/ADS-Simulation/'));
create foreign table gs_tables_db."TRNG_Covid360_ADS_simulation_jakarta_locatio",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/ADS-simulation-jakarta-locatio/'));
create foreign table gs_tables_db."TRNG_Covid360_ADS_simulation_risk_SNA",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/ADS-simulation-risk-SNA/'));
create foreign table gs_tables_db."TRNG_Covid360_ADS_simulation_stats",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/ADS-simulation-stats/'));
create foreign table gs_tables_db."TRNG_Covid360_ADS_simulation_with_risk",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/ADS-simulation-with-risk/'));
create foreign table gs_tables_db."TRNG_Covid360_ADS_simulation_with_risk_locat",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/ADS-simulation-with-risk-locat/'));
create foreign table gs_tables_db."TRNG_Covid360_ADS_SNA_Betweenness",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/ADS-SNA-Betweenness/'));
create foreign table gs_tables_db."TRNG_Covid360_ADS_SNA_Closeness",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/ADS-SNA-Closeness/'));
create foreign table gs_tables_db."TRNG_Covid360_ADS_SNA_EigenCentrality",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/ADS-SNA-EigenCentrality/'));
create foreign table gs_tables_db."TRNG_Covid360_ADS_SNA_LocalClusteringCoeffic",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/ADS-SNA-LocalClusteringCoeffic/'));
create foreign table gs_tables_db."TRNG_Covid360_ADS_SNA_Polulation_Generation",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/ADS-SNA-Polulation-Generation/'));
create foreign table gs_tables_db."TRNG_Covid360_EVN_PERSON_MOVEMENT_EVENTS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/EVN-PERSON-MOVEMENT-EVENTS/'));
create foreign table gs_tables_db."TRNG_Covid360_SEM_D_PERSON",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/SEM-D-PERSON/'));
create foreign table gs_tables_db."TRNG_Covid360_SEM_D_RISK_SCORE_TYPE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/SEM-D-RISK-SCORE-TYPE/'));
create foreign table gs_tables_db."TRNG_Covid360_SEM_D_SITE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/SEM-D-SITE/'));
create foreign table gs_tables_db."TRNG_Covid360_SEM_D_SOCIAL_GROUP",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/SEM-D-SOCIAL-GROUP/'));
create foreign table gs_tables_db."TRNG_Covid360_SEM_D_TIME",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/SEM-D-TIME/'));
create foreign table gs_tables_db."TRNG_Covid360_SEM_F_PERSON_RISK_SCORE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/SEM-F-PERSON-RISK-SCORE/'));
create foreign table gs_tables_db."TRNG_Covid360_SEM_F_SOCIAL_GROUP_RISK_SCORE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/SEM-F-SOCIAL-GROUP-RISK-SCORE/'));
create foreign table gs_tables_db."TRNG_Covid360_SEM_H_SITE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/SEM-H-SITE/'));
create foreign table gs_tables_db."TRNG_Covid360_SEM_R_PERSON_LOCATION_RISK_SCO",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/SEM-R-PERSON-LOCATION-RISK-SCO/'));
create foreign table gs_tables_db."TRNG_Covid360_SEM_R_PERSON_RISK_CALCULATION_",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/SEM-R-PERSON-RISK-CALCULATION-/'));
create foreign table gs_tables_db."TRNG_Covid360_SEM_R_PERSON_RISK_CALCULATION_",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/SEM-R-PERSON-RISK-CALCULATION-/'));
create foreign table gs_tables_db."TRNG_Covid360_SEM_R_PERSON_RISK_EXPOSURE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/SEM-R-PERSON-RISK-EXPOSURE/'));
create foreign table gs_tables_db."TRNG_Covid360_SEM_R_PERSON_SOCIAL_GROUP",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/SEM-R-PERSON-SOCIAL-GROUP/'));
create foreign table gs_tables_db."TRNG_Covid360_WRK_SNA_Edge_Weight",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/WRK-SNA-Edge-Weight/'));
create foreign table gs_tables_db."TRNG_Covid360_WRK_SNA_Node",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Covid360/WRK-SNA-Node/'));
replace view TRNG_Covid360.ADS_SNA_Betweenness as locking row for access select * from  gs_tables_db."TRNG_Covid360_ADS_SNA_Betweenness";
replace view TRNG_Covid360.ADS_SNA_Closeness as locking row for access select * from  gs_tables_db."TRNG_Covid360_ADS_SNA_Closeness";
replace view TRNG_Covid360.ADS_SNA_EigenCentrality as locking row for access select * from  gs_tables_db."TRNG_Covid360_ADS_SNA_EigenCentrality";
replace view TRNG_Covid360.ADS_SNA_LocalClusteringCoeffic as locking row for access select * from  gs_tables_db."TRNG_Covid360_ADS_SNA_LocalClusteringCoeffic";
replace view TRNG_Covid360.ADS_SNA_Polulation_Generation as locking row for access select * from  gs_tables_db."TRNG_Covid360_ADS_SNA_Polulation_Generation";
replace view TRNG_Covid360.ADS_Simulation as locking row for access select * from  gs_tables_db."TRNG_Covid360_ADS_Simulation";
replace view TRNG_Covid360.ADS_age_factor as locking row for access select * from  gs_tables_db."TRNG_Covid360_ADS_age_factor";
replace view TRNG_Covid360.ADS_scenarios as locking row for access select * from  gs_tables_db."TRNG_Covid360_ADS_scenarios";
replace view TRNG_Covid360.ADS_simulation_jakarta_locatio as locking row for access select * from  gs_tables_db."TRNG_Covid360_ADS_simulation_jakarta_locatio";
replace view TRNG_Covid360.ADS_simulation_risk_SNA as locking row for access select * from  gs_tables_db."TRNG_Covid360_ADS_simulation_risk_SNA";
replace view TRNG_Covid360.ADS_simulation_stats as locking row for access select * from  gs_tables_db."TRNG_Covid360_ADS_simulation_stats";
replace view TRNG_Covid360.ADS_simulation_with_risk as locking row for access select * from  gs_tables_db."TRNG_Covid360_ADS_simulation_with_risk";
replace view TRNG_Covid360.ADS_simulation_with_risk_locat as locking row for access select * from  gs_tables_db."TRNG_Covid360_ADS_simulation_with_risk_locat";
replace view TRNG_Covid360.EVN_PERSON_MOVEMENT_EVENTS as locking row for access select * from  gs_tables_db."TRNG_Covid360_EVN_PERSON_MOVEMENT_EVENTS";
replace view TRNG_Covid360.SEM_D_PERSON as locking row for access select * from  gs_tables_db."TRNG_Covid360_SEM_D_PERSON";
replace view TRNG_Covid360.SEM_D_RISK_SCORE_TYPE as locking row for access select * from  gs_tables_db."TRNG_Covid360_SEM_D_RISK_SCORE_TYPE";
replace view TRNG_Covid360.SEM_D_SITE as locking row for access select * from  gs_tables_db."TRNG_Covid360_SEM_D_SITE";
replace view TRNG_Covid360.SEM_D_SOCIAL_GROUP as locking row for access select * from  gs_tables_db."TRNG_Covid360_SEM_D_SOCIAL_GROUP";
replace view TRNG_Covid360.SEM_D_TIME as locking row for access select * from  gs_tables_db."TRNG_Covid360_SEM_D_TIME";
replace view TRNG_Covid360.SEM_F_PERSON_RISK_SCORE as locking row for access select * from  gs_tables_db."TRNG_Covid360_SEM_F_PERSON_RISK_SCORE";
replace view TRNG_Covid360.SEM_F_SOCIAL_GROUP_RISK_SCORE as locking row for access select * from  gs_tables_db."TRNG_Covid360_SEM_F_SOCIAL_GROUP_RISK_SCORE";
replace view TRNG_Covid360.SEM_H_SITE as locking row for access select * from  gs_tables_db."TRNG_Covid360_SEM_H_SITE";
replace view TRNG_Covid360.SEM_R_PERSON_LOCATION_RISK_SCO as locking row for access select * from  gs_tables_db."TRNG_Covid360_SEM_R_PERSON_LOCATION_RISK_SCO";
replace view TRNG_Covid360.SEM_R_PERSON_RISK_CALCULATION_ as locking row for access select * from  gs_tables_db."TRNG_Covid360_SEM_R_PERSON_RISK_CALCULATION_";
replace view TRNG_Covid360.SEM_R_PERSON_RISK_CALCULATION_ as locking row for access select * from  gs_tables_db."TRNG_Covid360_SEM_R_PERSON_RISK_CALCULATION_";
replace view TRNG_Covid360.SEM_R_PERSON_RISK_EXPOSURE as locking row for access select * from  gs_tables_db."TRNG_Covid360_SEM_R_PERSON_RISK_EXPOSURE";
replace view TRNG_Covid360.SEM_R_PERSON_SOCIAL_GROUP as locking row for access select * from  gs_tables_db."TRNG_Covid360_SEM_R_PERSON_SOCIAL_GROUP";
replace view TRNG_Covid360.WRK_SNA_Edge_Weight as locking row for access select * from  gs_tables_db."TRNG_Covid360_WRK_SNA_Edge_Weight";
replace view TRNG_Covid360.WRK_SNA_Node as locking row for access select * from  gs_tables_db."TRNG_Covid360_WRK_SNA_Node";
