create database TRNG_Oil_Industry from demonow as perm=0;
create foreign table gs_tables_db."TRNG_Oil_Industry_ac_anomaly",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/ac-anomaly/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_ac_anomaly_lookup",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/ac-anomaly-lookup/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_ac_anomaly_pred",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/ac-anomaly-pred/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_ac_economic",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/ac-economic/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_AC_ECONOMIC_DC3",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/AC-ECONOMIC-DC3/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_AC_ECONOMIC_detail",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/AC-ECONOMIC-detail/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_ac_economic_pred",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/ac-economic-pred/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_ac_exception",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/ac-exception/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_AC_features",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/AC-features/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_AC_KEYWORD_PATH",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/AC-KEYWORD-PATH/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_ac_monthly",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/ac-monthly/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_AC_Phase_dir",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/AC-Phase-dir/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_ac_property",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/ac-property/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_DDaaS_Log_Tbl",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/DDaaS-Log-Tbl/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_hookload_hist_Histogram",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/hookload-hist-Histogram/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_ML_anomaly",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/ML-anomaly/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_Proc_Error_Tbl",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/Proc-Error-Tbl/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_Rig_States_Dictionary",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/Rig-States-Dictionary/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_Rig_States_Parameters",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/Rig-States-Parameters/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_Rig_States_tripout_depth",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/Rig-States-tripout-depth/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_Rig_State_Micro_Inter_Def",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/Rig-State-Micro-Inter-Def/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_Rig_State_StandLength",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/Rig-State-StandLength/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_SRFC_SENSOR_PARMS_PPI_FLAT",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/SRFC-SENSOR-PARMS-PPI-FLAT/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_Srfc_Sensor_Rig_Inter_States",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/Srfc-Sensor-Rig-Inter-States/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_SRFC_SENSOR_RIG_STATES",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/SRFC-SENSOR-RIG-STATES/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_test1",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/test1/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_WELLS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/WELLS/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_Well_calc_info",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/Well-calc-info/'));
create foreign table gs_tables_db."TRNG_Oil_Industry_WELL_RIGS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-Oil-Industry/WELL-RIGS/'));
replace view TRNG_Oil_Industry.AC_ECONOMIC_DC3 as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_AC_ECONOMIC_DC3";
replace view TRNG_Oil_Industry.AC_ECONOMIC_detail as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_AC_ECONOMIC_detail";
replace view TRNG_Oil_Industry.AC_KEYWORD_PATH as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_AC_KEYWORD_PATH";
replace view TRNG_Oil_Industry.AC_Phase_dir as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_AC_Phase_dir";
replace view TRNG_Oil_Industry.AC_features as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_AC_features";
replace view TRNG_Oil_Industry.DDaaS_Log_Tbl as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_DDaaS_Log_Tbl";
replace view TRNG_Oil_Industry.ML_anomaly as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_ML_anomaly";
replace view TRNG_Oil_Industry.Proc_Error_Tbl as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_Proc_Error_Tbl";
replace view TRNG_Oil_Industry.Rig_State_Micro_Inter_Def as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_Rig_State_Micro_Inter_Def";
replace view TRNG_Oil_Industry.Rig_State_StandLength as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_Rig_State_StandLength";
replace view TRNG_Oil_Industry.Rig_States_Dictionary as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_Rig_States_Dictionary";
replace view TRNG_Oil_Industry.Rig_States_Parameters as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_Rig_States_Parameters";
replace view TRNG_Oil_Industry.Rig_States_tripout_depth as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_Rig_States_tripout_depth";
replace view TRNG_Oil_Industry.SRFC_SENSOR_PARMS_PPI_FLAT as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_SRFC_SENSOR_PARMS_PPI_FLAT";
replace view TRNG_Oil_Industry.SRFC_SENSOR_RIG_STATES as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_SRFC_SENSOR_RIG_STATES";
replace view TRNG_Oil_Industry.Srfc_Sensor_Rig_Inter_States as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_Srfc_Sensor_Rig_Inter_States";
replace view TRNG_Oil_Industry.WELLS as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_WELLS";
replace view TRNG_Oil_Industry.WELL_RIGS as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_WELL_RIGS";
replace view TRNG_Oil_Industry.Well_calc_info as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_Well_calc_info";
replace view TRNG_Oil_Industry.ac_anomaly as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_ac_anomaly";
replace view TRNG_Oil_Industry.ac_anomaly_lookup as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_ac_anomaly_lookup";
replace view TRNG_Oil_Industry.ac_anomaly_pred as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_ac_anomaly_pred";
replace view TRNG_Oil_Industry.ac_economic as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_ac_economic";
replace view TRNG_Oil_Industry.ac_economic_pred as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_ac_economic_pred";
replace view TRNG_Oil_Industry.ac_exception as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_ac_exception";
replace view TRNG_Oil_Industry.ac_monthly as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_ac_monthly";
replace view TRNG_Oil_Industry.ac_property as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_ac_property";
replace view TRNG_Oil_Industry.hookload_hist_Histogram as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_hookload_hist_Histogram";
replace view TRNG_Oil_Industry.test1 as locking row for access select * from  gs_tables_db."TRNG_Oil_Industry_test1";
