create database TRNG_CONNECTEDFACTORY from demonow as perm=0;
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_beaWelllimits",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/beaWelllimits/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_bea_tmpColumns",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/bea-tmpColumns/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_bea_tmpCombine",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/bea-tmpCombine/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_bea_tmpdata",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/bea-tmpdata/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_bea_tmphists",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/bea-tmphists/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_bea_wbl_prepdata",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/bea-wbl-prepdata/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_cf_0.9",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/cf-0.9/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_cf_ti_0.8",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/cf-ti-0.8/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_cf_ti_0.85",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/cf-ti-0.85/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_cf_ti_0.9",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/cf-ti-0.9/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_cf_ti_0.95",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/cf-ti-0.95/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_gehc_full_export",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/gehc-full-export/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_ml__td_glm0_1627517161702454",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/ml--td-glm0-1627517161702454/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_ml__td_sqlmr_out__162751676320",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/ml--td-sqlmr-out--162751676320/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_CMN_T_SIM_AGG_ADS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-CMN-T-SIM-AGG-ADS/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM1_Part_A_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM1-Part-A-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM1_Part_B1_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM1-Part-B1-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM1_Part_B2_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM1-Part-B2-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM1_Part_C1_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM1-Part-C1-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_A_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM2-Part-A-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_A_Scored_Data_",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM2-Part-A-Scored-Data-/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_B1_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM2-Part-B1-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_B1_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM2-Part-B1-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_B2_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM2-Part-B2-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_B2_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM2-Part-B2-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_C1_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM2-Part-C1-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_C1_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM2-Part-C1-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM3_Part_A_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM3-Part-A-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM3_Part_B1_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM3-Part-B1-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM3_Part_B2_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM3-Part-B2-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM3_Part_C1_Scored_Data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-ML-QM3-Part-C1-Scored-Data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_SIM_T_SIM_ADS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-SIM-T-SIM-ADS/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_SIM_T_SIM_AGG_ADS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-SIM-T-SIM-AGG-ADS/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_SIM_T_SIM_AGG_DATASET",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-SIM-T-SIM-AGG-DATASET/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_TAB_QM_RAW",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-TAB-QM-RAW/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_TAB_QM_SCORED",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-TAB-QM-SCORED/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_TAB_TIME_INFO_QM1_SM",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-TAB-TIME-INFO-QM1-SM/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_TAB_TIME_INFO_QM2_SM",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-TAB-TIME-INFO-QM2-SM/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_TAB_TIME_INFO_QM3_SM",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/MVP-TAB-TIME-INFO-QM3-SM/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_cox_coef",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-cox-coef/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_cox_pred",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-cox-pred/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_cox_predict",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-cox-predict/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_cox_predict_365",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-cox-predict-365/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_dt_imp",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-dt-imp/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_dt_pred",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-dt-pred/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_dt_pred_imp",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-dt-pred-imp/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_log_pred_updated",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-log-pred-updated/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_lrs_pred_imp",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-lrs-pred-imp/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_lr_coef",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-lr-coef/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_lr_pred",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-lr-pred/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_lr_pred_ext",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-lr-pred-ext/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_lr_pred_imp",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-lr-pred-imp/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_rfs_pred_imp",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-rfs-pred-imp/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_rf_imp",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-rf-imp/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_rf_pred",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-rf-pred/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_rf_pred_imp",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-rf-pred-imp/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_rf_pred_sur",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-rf-pred-sur/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_rf_pred_updated",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-rf-pred-updated/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_sts_pred_imp",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-sts-pred-imp/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_xg_pred",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-xg-pred/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_xg_pred_ext",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-xg-pred-ext/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_xg_pred_updated",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-acs-xg-pred-updated/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_asset_attribute_data_gener",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-asset-attribute-data-gener/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_asset_attribute_data_usage",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-asset-attribute-data-usage/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_asset_attribute_data_weath",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-asset-attribute-data-weath/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_asset_data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-asset-data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_maintenance_depots",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-maintenance-depots/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_out",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-out/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_planned_data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-planned-data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_planned_data_component_bre",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-planned-data-component-bre/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_planned_data_ext",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-planned-data-ext/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_problem_trucks",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-problem-trucks/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_problem_trucks_data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-problem-trucks-data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_repair_data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-repair-data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_replacement_data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-replacement-data/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_survival_rf_pred",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-survival-rf-pred/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_survival_rf_pred1",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-survival-rf-pred1/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_survival_ts_pred",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-survival-ts-pred/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_trailer_type",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-trailer-type/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_truckswithData",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-truckswithData/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_truck_attribute_data_gener",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-truck-attribute-data-gener/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_truck_attribute_data_usage",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-truck-attribute-data-usage/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_pam_truck_route",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/pam-truck-route/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_planned_data_new",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/planned-data-new/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_rf_pam_survival_pred",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/rf-pam-survival-pred/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_rf_pred_updated",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/rf-pred-updated/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_seq_integers",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/seq-integers/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_survival_pred_updated",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/survival-pred-updated/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_ALERT_PARAMETER",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/TAF-ALERT-PARAMETER/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_ANALYTIC_ID_LOOKUP",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/TAF-ANALYTIC-ID-LOOKUP/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_GRP_DEFN",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/TAF-GRP-DEFN/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_GRP_INSTANCE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/TAF-GRP-INSTANCE/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_LAST_VALID_RUN",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/TAF-LAST-VALID-RUN/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_PARAMETER",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/TAF-PARAMETER/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_RESULT_DESCRIPTIVE_STATIST",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/TAF-RESULT-DESCRIPTIVE-STATIST/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_RESULT_HISTGR_MODELS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/TAF-RESULT-HISTGR-MODELS/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_RESULT_KS_TEST",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/TAF-RESULT-KS-TEST/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_taf_result_logitval_rpt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/taf-result-logitval-rpt/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_taf_result_logitval_txt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/taf-result-logitval-txt/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_RESULT_MC_SIM",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/TAF-RESULT-MC-SIM/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_taf_result_pareto",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/taf-result-pareto/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_RESULT_SPC_XmR",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/TAF-RESULT-SPC-XmR/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_taf_result_weibull",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/taf-result-weibull/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_taf_run_status",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/taf-run-status/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_SPC_XmR_LIMITS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/TAF-SPC-XmR-LIMITS/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_taf_work_logValSTr",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/taf-work-logValSTr/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_tmp",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/tmp/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_TWM_CUSTOMER",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/TWM-CUSTOMER/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_VARIABLE_MAP",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/VARIABLE-MAP/'));
create foreign table gs_tables_db."TRNG_CONNECTEDFACTORY_xg_pred_updated",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-CONNECTEDFACTORY/xg-pred-updated/'));
replace view TRNG_CONNECTEDFACTORY.MVP_CMN_T_SIM_AGG_ADS as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_CMN_T_SIM_AGG_ADS";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM1_Part_A_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM1_Part_A_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM1_Part_B1_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM1_Part_B1_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM1_Part_B2_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM1_Part_B2_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM1_Part_C1_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM1_Part_C1_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM2_Part_A_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_A_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM2_Part_A_Scored_Data_ as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_A_Scored_Data_";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM2_Part_B1_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_B1_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM2_Part_B1_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_B1_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM2_Part_B2_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_B2_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM2_Part_B2_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_B2_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM2_Part_C1_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_C1_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM2_Part_C1_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM2_Part_C1_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM3_Part_A_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM3_Part_A_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM3_Part_B1_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM3_Part_B1_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM3_Part_B2_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM3_Part_B2_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_ML_QM3_Part_C1_Scored_Data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_ML_QM3_Part_C1_Scored_Data";
replace view TRNG_CONNECTEDFACTORY.MVP_SIM_T_SIM_ADS as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_SIM_T_SIM_ADS";
replace view TRNG_CONNECTEDFACTORY.MVP_SIM_T_SIM_AGG_ADS as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_SIM_T_SIM_AGG_ADS";
replace view TRNG_CONNECTEDFACTORY.MVP_SIM_T_SIM_AGG_DATASET as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_SIM_T_SIM_AGG_DATASET";
replace view TRNG_CONNECTEDFACTORY.MVP_TAB_QM_RAW as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_TAB_QM_RAW";
replace view TRNG_CONNECTEDFACTORY.MVP_TAB_QM_SCORED as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_TAB_QM_SCORED";
replace view TRNG_CONNECTEDFACTORY.MVP_TAB_TIME_INFO_QM1_SM as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_TAB_TIME_INFO_QM1_SM";
replace view TRNG_CONNECTEDFACTORY.MVP_TAB_TIME_INFO_QM2_SM as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_TAB_TIME_INFO_QM2_SM";
replace view TRNG_CONNECTEDFACTORY.MVP_TAB_TIME_INFO_QM3_SM as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_MVP_TAB_TIME_INFO_QM3_SM";
replace view TRNG_CONNECTEDFACTORY.TAF_ALERT_PARAMETER as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_ALERT_PARAMETER";
replace view TRNG_CONNECTEDFACTORY.TAF_ANALYTIC_ID_LOOKUP as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_ANALYTIC_ID_LOOKUP";
replace view TRNG_CONNECTEDFACTORY.TAF_GRP_DEFN as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_GRP_DEFN";
replace view TRNG_CONNECTEDFACTORY.TAF_GRP_INSTANCE as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_GRP_INSTANCE";
replace view TRNG_CONNECTEDFACTORY.TAF_LAST_VALID_RUN as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_LAST_VALID_RUN";
replace view TRNG_CONNECTEDFACTORY.TAF_PARAMETER as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_PARAMETER";
replace view TRNG_CONNECTEDFACTORY.TAF_RESULT_DESCRIPTIVE_STATIST as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_RESULT_DESCRIPTIVE_STATIST";
replace view TRNG_CONNECTEDFACTORY.TAF_RESULT_HISTGR_MODELS as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_RESULT_HISTGR_MODELS";
replace view TRNG_CONNECTEDFACTORY.TAF_RESULT_KS_TEST as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_RESULT_KS_TEST";
replace view TRNG_CONNECTEDFACTORY.TAF_RESULT_MC_SIM as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_RESULT_MC_SIM";
replace view TRNG_CONNECTEDFACTORY.TAF_RESULT_SPC_XmR as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_RESULT_SPC_XmR";
replace view TRNG_CONNECTEDFACTORY.TAF_SPC_XmR_LIMITS as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_TAF_SPC_XmR_LIMITS";
replace view TRNG_CONNECTEDFACTORY.TWM_CUSTOMER as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_TWM_CUSTOMER";
replace view TRNG_CONNECTEDFACTORY.VARIABLE_MAP as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_VARIABLE_MAP";
replace view TRNG_CONNECTEDFACTORY.beaWelllimits as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_beaWelllimits";
replace view TRNG_CONNECTEDFACTORY.bea_tmpColumns as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_bea_tmpColumns";
replace view TRNG_CONNECTEDFACTORY.bea_tmpCombine as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_bea_tmpCombine";
replace view TRNG_CONNECTEDFACTORY.bea_tmpdata as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_bea_tmpdata";
replace view TRNG_CONNECTEDFACTORY.bea_tmphists as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_bea_tmphists";
replace view TRNG_CONNECTEDFACTORY.bea_wbl_prepdata as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_bea_wbl_prepdata";
replace view TRNG_CONNECTEDFACTORY.cf_0.9 as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_cf_0.9";
replace view TRNG_CONNECTEDFACTORY.cf_ti_0.8 as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_cf_ti_0.8";
replace view TRNG_CONNECTEDFACTORY.cf_ti_0.85 as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_cf_ti_0.85";
replace view TRNG_CONNECTEDFACTORY.cf_ti_0.9 as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_cf_ti_0.9";
replace view TRNG_CONNECTEDFACTORY.cf_ti_0.95 as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_cf_ti_0.95";
replace view TRNG_CONNECTEDFACTORY.gehc_full_export as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_gehc_full_export";
replace view TRNG_CONNECTEDFACTORY.ml__td_glm0_1627517161702454 as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_ml__td_glm0_1627517161702454";
replace view TRNG_CONNECTEDFACTORY.ml__td_sqlmr_out__162751676320 as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_ml__td_sqlmr_out__162751676320";
replace view TRNG_CONNECTEDFACTORY.pam_acs_cox_coef as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_cox_coef";
replace view TRNG_CONNECTEDFACTORY.pam_acs_cox_pred as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_cox_pred";
replace view TRNG_CONNECTEDFACTORY.pam_acs_cox_predict as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_cox_predict";
replace view TRNG_CONNECTEDFACTORY.pam_acs_cox_predict_365 as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_cox_predict_365";
replace view TRNG_CONNECTEDFACTORY.pam_acs_dt_imp as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_dt_imp";
replace view TRNG_CONNECTEDFACTORY.pam_acs_dt_pred as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_dt_pred";
replace view TRNG_CONNECTEDFACTORY.pam_acs_dt_pred_imp as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_dt_pred_imp";
replace view TRNG_CONNECTEDFACTORY.pam_acs_log_pred_updated as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_log_pred_updated";
replace view TRNG_CONNECTEDFACTORY.pam_acs_lr_coef as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_lr_coef";
replace view TRNG_CONNECTEDFACTORY.pam_acs_lr_pred as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_lr_pred";
replace view TRNG_CONNECTEDFACTORY.pam_acs_lr_pred_ext as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_lr_pred_ext";
replace view TRNG_CONNECTEDFACTORY.pam_acs_lr_pred_imp as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_lr_pred_imp";
replace view TRNG_CONNECTEDFACTORY.pam_acs_lrs_pred_imp as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_lrs_pred_imp";
replace view TRNG_CONNECTEDFACTORY.pam_acs_rf_imp as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_rf_imp";
replace view TRNG_CONNECTEDFACTORY.pam_acs_rf_pred as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_rf_pred";
replace view TRNG_CONNECTEDFACTORY.pam_acs_rf_pred_imp as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_rf_pred_imp";
replace view TRNG_CONNECTEDFACTORY.pam_acs_rf_pred_sur as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_rf_pred_sur";
replace view TRNG_CONNECTEDFACTORY.pam_acs_rf_pred_updated as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_rf_pred_updated";
replace view TRNG_CONNECTEDFACTORY.pam_acs_rfs_pred_imp as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_rfs_pred_imp";
replace view TRNG_CONNECTEDFACTORY.pam_acs_sts_pred_imp as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_sts_pred_imp";
replace view TRNG_CONNECTEDFACTORY.pam_acs_xg_pred as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_xg_pred";
replace view TRNG_CONNECTEDFACTORY.pam_acs_xg_pred_ext as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_xg_pred_ext";
replace view TRNG_CONNECTEDFACTORY.pam_acs_xg_pred_updated as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_acs_xg_pred_updated";
replace view TRNG_CONNECTEDFACTORY.pam_asset_attribute_data_gener as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_asset_attribute_data_gener";
replace view TRNG_CONNECTEDFACTORY.pam_asset_attribute_data_usage as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_asset_attribute_data_usage";
replace view TRNG_CONNECTEDFACTORY.pam_asset_attribute_data_weath as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_asset_attribute_data_weath";
replace view TRNG_CONNECTEDFACTORY.pam_asset_data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_asset_data";
replace view TRNG_CONNECTEDFACTORY.pam_maintenance_depots as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_maintenance_depots";
replace view TRNG_CONNECTEDFACTORY.pam_out as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_out";
replace view TRNG_CONNECTEDFACTORY.pam_planned_data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_planned_data";
replace view TRNG_CONNECTEDFACTORY.pam_planned_data_component_bre as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_planned_data_component_bre";
replace view TRNG_CONNECTEDFACTORY.pam_planned_data_ext as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_planned_data_ext";
replace view TRNG_CONNECTEDFACTORY.pam_problem_trucks as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_problem_trucks";
replace view TRNG_CONNECTEDFACTORY.pam_problem_trucks_data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_problem_trucks_data";
replace view TRNG_CONNECTEDFACTORY.pam_repair_data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_repair_data";
replace view TRNG_CONNECTEDFACTORY.pam_replacement_data as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_replacement_data";
replace view TRNG_CONNECTEDFACTORY.pam_survival_rf_pred as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_survival_rf_pred";
replace view TRNG_CONNECTEDFACTORY.pam_survival_rf_pred1 as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_survival_rf_pred1";
replace view TRNG_CONNECTEDFACTORY.pam_survival_ts_pred as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_survival_ts_pred";
replace view TRNG_CONNECTEDFACTORY.pam_trailer_type as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_trailer_type";
replace view TRNG_CONNECTEDFACTORY.pam_truck_attribute_data_gener as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_truck_attribute_data_gener";
replace view TRNG_CONNECTEDFACTORY.pam_truck_attribute_data_usage as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_truck_attribute_data_usage";
replace view TRNG_CONNECTEDFACTORY.pam_truck_route as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_truck_route";
replace view TRNG_CONNECTEDFACTORY.pam_truckswithData as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_pam_truckswithData";
replace view TRNG_CONNECTEDFACTORY.planned_data_new as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_planned_data_new";
replace view TRNG_CONNECTEDFACTORY.rf_pam_survival_pred as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_rf_pam_survival_pred";
replace view TRNG_CONNECTEDFACTORY.rf_pred_updated as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_rf_pred_updated";
replace view TRNG_CONNECTEDFACTORY.seq_integers as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_seq_integers";
replace view TRNG_CONNECTEDFACTORY.survival_pred_updated as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_survival_pred_updated";
replace view TRNG_CONNECTEDFACTORY.taf_result_logitval_rpt as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_taf_result_logitval_rpt";
replace view TRNG_CONNECTEDFACTORY.taf_result_logitval_txt as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_taf_result_logitval_txt";
replace view TRNG_CONNECTEDFACTORY.taf_result_pareto as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_taf_result_pareto";
replace view TRNG_CONNECTEDFACTORY.taf_result_weibull as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_taf_result_weibull";
replace view TRNG_CONNECTEDFACTORY.taf_run_status as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_taf_run_status";
replace view TRNG_CONNECTEDFACTORY.taf_work_logValSTr as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_taf_work_logValSTr";
replace view TRNG_CONNECTEDFACTORY.tmp as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_tmp";
replace view TRNG_CONNECTEDFACTORY.xg_pred_updated as locking row for access select * from  gs_tables_db."TRNG_CONNECTEDFACTORY_xg_pred_updated";
