create database TRNG_HealthcareSurgery from demonow as perm=0;
create foreign table gs_tables_db."TRNG_HealthcareSurgery_healthcarecfilter",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HealthcareSurgery/healthcarecfilter/'));
create foreign table gs_tables_db."TRNG_HealthcareSurgery_healthcare_all_paths",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HealthcareSurgery/healthcare-all-paths/'));
create foreign table gs_tables_db."TRNG_HealthcareSurgery_healthcare_all_paths_tf",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HealthcareSurgery/healthcare-all-paths-tf/'));
create foreign table gs_tables_db."TRNG_HealthcareSurgery_healthcare_all_paths_tfidf",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HealthcareSurgery/healthcare-all-paths-tfidf/'));
create foreign table gs_tables_db."TRNG_HealthcareSurgery_healthcare_all_paths_tfidf_inp",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HealthcareSurgery/healthcare-all-paths-tfidf-inp/'));
create foreign table gs_tables_db."TRNG_HealthcareSurgery_healthcare_all_paths_token",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HealthcareSurgery/healthcare-all-paths-token/'));
create foreign table gs_tables_db."TRNG_HealthcareSurgery_healthcare_all_paths_token_cle",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HealthcareSurgery/healthcare-all-paths-token-cle/'));
create foreign table gs_tables_db."TRNG_HealthcareSurgery_healthcare_modularity",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HealthcareSurgery/healthcare-modularity/'));
create foreign table gs_tables_db."TRNG_HealthcareSurgery_healthcare_sample_recordid",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HealthcareSurgery/healthcare-sample-recordid/'));
create foreign table gs_tables_db."TRNG_HealthcareSurgery_healthcare_surgery_events",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HealthcareSurgery/healthcare-surgery-events/'));
create foreign table gs_tables_db."TRNG_HealthcareSurgery_surgery_events_cluster",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HealthcareSurgery/surgery-events-cluster/'));
create foreign table gs_tables_db."TRNG_HealthcareSurgery_surgery_events_model",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HealthcareSurgery/surgery-events-model/'));
replace view TRNG_HealthcareSurgery.healthcare_all_paths as locking row for access select * from  gs_tables_db."TRNG_HealthcareSurgery_healthcare_all_paths";
replace view TRNG_HealthcareSurgery.healthcare_all_paths_tf as locking row for access select * from  gs_tables_db."TRNG_HealthcareSurgery_healthcare_all_paths_tf";
replace view TRNG_HealthcareSurgery.healthcare_all_paths_tfidf as locking row for access select * from  gs_tables_db."TRNG_HealthcareSurgery_healthcare_all_paths_tfidf";
replace view TRNG_HealthcareSurgery.healthcare_all_paths_tfidf_inp as locking row for access select * from  gs_tables_db."TRNG_HealthcareSurgery_healthcare_all_paths_tfidf_inp";
replace view TRNG_HealthcareSurgery.healthcare_all_paths_token as locking row for access select * from  gs_tables_db."TRNG_HealthcareSurgery_healthcare_all_paths_token";
replace view TRNG_HealthcareSurgery.healthcare_all_paths_token_cle as locking row for access select * from  gs_tables_db."TRNG_HealthcareSurgery_healthcare_all_paths_token_cle";
replace view TRNG_HealthcareSurgery.healthcare_modularity as locking row for access select * from  gs_tables_db."TRNG_HealthcareSurgery_healthcare_modularity";
replace view TRNG_HealthcareSurgery.healthcare_sample_recordid as locking row for access select * from  gs_tables_db."TRNG_HealthcareSurgery_healthcare_sample_recordid";
replace view TRNG_HealthcareSurgery.healthcare_surgery_events as locking row for access select * from  gs_tables_db."TRNG_HealthcareSurgery_healthcare_surgery_events";
replace view TRNG_HealthcareSurgery.healthcarecfilter as locking row for access select * from  gs_tables_db."TRNG_HealthcareSurgery_healthcarecfilter";
replace view TRNG_HealthcareSurgery.surgery_events_cluster as locking row for access select * from  gs_tables_db."TRNG_HealthcareSurgery_surgery_events_cluster";
replace view TRNG_HealthcareSurgery.surgery_events_model as locking row for access select * from  gs_tables_db."TRNG_HealthcareSurgery_surgery_events_model";
