create database TRNG_RETAILDSE_DEV from demonow as perm=0;
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_ASSOC_10PURCHASES",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/ASSOC-10PURCHASES/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_CUSTOMER_MASTER_ATTRIBUTES",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/CUSTOMER-MASTER-ATTRIBUTES/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_CUSTOMER_PURCHASES_FLAT",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/CUSTOMER-PURCHASES-FLAT/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_CUST_CC_EVENTS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/CUST-CC-EVENTS/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_CUST_ONLINE_EVENTS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/CUST-ONLINE-EVENTS/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_CUST_STORE_EVENTS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/CUST-STORE-EVENTS/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_DecisionTreeScore1",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/DecisionTreeScore1/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_DecisionTreeScore1_rpt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/DecisionTreeScore1-rpt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_FactorAnalysisScore1",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/FactorAnalysisScore1/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_FactorAnalysisScore1_rpt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/FactorAnalysisScore1-rpt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_LogisticOut1_rpt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/LogisticOut1-rpt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_LogisticOut1_txt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/LogisticOut1-txt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_LogisticScore1_txt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/LogisticScore1-txt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_LREGModel1_rpt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/LREGModel1-rpt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_LREGModel1_txt",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/LREGModel1-txt/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_NEW_CUSTOMERS_MASTER",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/NEW-CUSTOMERS-MASTER/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_NEW_RETAIL_ALLCH_EVENT_DESC_MA",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/NEW-RETAIL-ALLCH-EVENT-DESC-MA/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_NEW_RETAIL_CUST_EVENTS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/NEW-RETAIL-CUST-EVENTS/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_TEMP_ERASE_CUSTOMERS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/TEMP-ERASE-CUSTOMERS/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreFrequency",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/TwmExploreFrequency/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreHistogram",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/TwmExploreHistogram/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreStatistics",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/TwmExploreStatistics/'));
create foreign table gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreValues",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-RETAILDSE-DEV/TwmExploreValues/'));
replace view TRNG_RETAILDSE_DEV.ASSOC_10PURCHASES as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_ASSOC_10PURCHASES";
replace view TRNG_RETAILDSE_DEV.CUSTOMER_MASTER_ATTRIBUTES as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_CUSTOMER_MASTER_ATTRIBUTES";
replace view TRNG_RETAILDSE_DEV.CUSTOMER_PURCHASES_FLAT as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_CUSTOMER_PURCHASES_FLAT";
replace view TRNG_RETAILDSE_DEV.CUST_CC_EVENTS as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_CUST_CC_EVENTS";
replace view TRNG_RETAILDSE_DEV.CUST_ONLINE_EVENTS as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_CUST_ONLINE_EVENTS";
replace view TRNG_RETAILDSE_DEV.CUST_STORE_EVENTS as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_CUST_STORE_EVENTS";
replace view TRNG_RETAILDSE_DEV.DecisionTreeScore1 as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_DecisionTreeScore1";
replace view TRNG_RETAILDSE_DEV.DecisionTreeScore1_rpt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_DecisionTreeScore1_rpt";
replace view TRNG_RETAILDSE_DEV.FactorAnalysisScore1 as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_FactorAnalysisScore1";
replace view TRNG_RETAILDSE_DEV.FactorAnalysisScore1_rpt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_FactorAnalysisScore1_rpt";
replace view TRNG_RETAILDSE_DEV.LREGModel1_rpt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_LREGModel1_rpt";
replace view TRNG_RETAILDSE_DEV.LREGModel1_txt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_LREGModel1_txt";
replace view TRNG_RETAILDSE_DEV.LogisticOut1_rpt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_LogisticOut1_rpt";
replace view TRNG_RETAILDSE_DEV.LogisticOut1_txt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_LogisticOut1_txt";
replace view TRNG_RETAILDSE_DEV.LogisticScore1_txt as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_LogisticScore1_txt";
replace view TRNG_RETAILDSE_DEV.NEW_CUSTOMERS_MASTER as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_NEW_CUSTOMERS_MASTER";
replace view TRNG_RETAILDSE_DEV.NEW_RETAIL_ALLCH_EVENT_DESC_MA as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_NEW_RETAIL_ALLCH_EVENT_DESC_MA";
replace view TRNG_RETAILDSE_DEV.NEW_RETAIL_CUST_EVENTS as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_NEW_RETAIL_CUST_EVENTS";
replace view TRNG_RETAILDSE_DEV.TEMP_ERASE_CUSTOMERS as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_TEMP_ERASE_CUSTOMERS";
replace view TRNG_RETAILDSE_DEV.TwmExploreFrequency as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreFrequency";
replace view TRNG_RETAILDSE_DEV.TwmExploreHistogram as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreHistogram";
replace view TRNG_RETAILDSE_DEV.TwmExploreStatistics as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreStatistics";
replace view TRNG_RETAILDSE_DEV.TwmExploreValues as locking row for access select * from  gs_tables_db."TRNG_RETAILDSE_DEV_TwmExploreValues";
