create database TRNG_TelcoNetwork from demonow as perm=0;
create foreign table gs_tables_db."TRNG_TelcoNetwork_APPS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/APPS/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_hourly_customers_on_cell_sites",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/hourly-customers-on-cell-sites/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_JOURNEY_START_DETAILS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/JOURNEY-START-DETAILS/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_max_customers_cellsite_connreq",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/max-customers-cellsite-connreq/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_max_customers_cellsite_handove",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/max-customers-cellsite-handove/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CELL_TOWERS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/NEXTGEN-MOBILE-NW-CELL-TOWERS/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CONGESTION_B",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/NEXTGEN-MOBILE-NW-CONGESTION-B/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_COVERAGE_MAP",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/NEXTGEN-MOBILE-NW-COVERAGE-MAP/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CUST_JOURNEY",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/NEXTGEN-MOBILE-NW-CUST-JOURNEY/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CUST_JOURNEY",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/NEXTGEN-MOBILE-NW-CUST-JOURNEY/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CUST_JOURNEY",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/NEXTGEN-MOBILE-NW-CUST-JOURNEY/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CUST_JOURNEY",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/NEXTGEN-MOBILE-NW-CUST-JOURNEY/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CUST_NAVIGAT",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/NEXTGEN-MOBILE-NW-CUST-NAVIGAT/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_GPSLOC_CUM_E",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/NEXTGEN-MOBILE-NW-GPSLOC-CUM-E/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_POSTAL_ZONES",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/NEXTGEN-MOBILE-NW-POSTAL-ZONES/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_peak_customers_in_economic_zon",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/peak-customers-in-economic-zon/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_peak_customers_on_cell_sites",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/peak-customers-on-cell-sites/'));
create foreign table gs_tables_db."TRNG_TelcoNetwork_peak_smartphone_app_usage",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-TelcoNetwork/peak-smartphone-app-usage/'));
replace view TRNG_TelcoNetwork.APPS as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_APPS";
replace view TRNG_TelcoNetwork.JOURNEY_START_DETAILS as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_JOURNEY_START_DETAILS";
replace view TRNG_TelcoNetwork.NEXTGEN_MOBILE_NW_CELL_TOWERS as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CELL_TOWERS";
replace view TRNG_TelcoNetwork.NEXTGEN_MOBILE_NW_CONGESTION_B as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CONGESTION_B";
replace view TRNG_TelcoNetwork.NEXTGEN_MOBILE_NW_COVERAGE_MAP as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_COVERAGE_MAP";
replace view TRNG_TelcoNetwork.NEXTGEN_MOBILE_NW_CUST_JOURNEY as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CUST_JOURNEY";
replace view TRNG_TelcoNetwork.NEXTGEN_MOBILE_NW_CUST_JOURNEY as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CUST_JOURNEY";
replace view TRNG_TelcoNetwork.NEXTGEN_MOBILE_NW_CUST_JOURNEY as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CUST_JOURNEY";
replace view TRNG_TelcoNetwork.NEXTGEN_MOBILE_NW_CUST_JOURNEY as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CUST_JOURNEY";
replace view TRNG_TelcoNetwork.NEXTGEN_MOBILE_NW_CUST_NAVIGAT as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_CUST_NAVIGAT";
replace view TRNG_TelcoNetwork.NEXTGEN_MOBILE_NW_GPSLOC_CUM_E as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_GPSLOC_CUM_E";
replace view TRNG_TelcoNetwork.NEXTGEN_MOBILE_NW_POSTAL_ZONES as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_NEXTGEN_MOBILE_NW_POSTAL_ZONES";
replace view TRNG_TelcoNetwork.hourly_customers_on_cell_sites as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_hourly_customers_on_cell_sites";
replace view TRNG_TelcoNetwork.max_customers_cellsite_connreq as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_max_customers_cellsite_connreq";
replace view TRNG_TelcoNetwork.max_customers_cellsite_handove as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_max_customers_cellsite_handove";
replace view TRNG_TelcoNetwork.peak_customers_in_economic_zon as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_peak_customers_in_economic_zon";
replace view TRNG_TelcoNetwork.peak_customers_on_cell_sites as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_peak_customers_on_cell_sites";
replace view TRNG_TelcoNetwork.peak_smartphone_app_usage as locking row for access select * from  gs_tables_db."TRNG_TelcoNetwork_peak_smartphone_app_usage";
