create database TRNG_COVID19_GDC from demonow as perm=0;
create foreign table gs_tables_db."TRNG_COVID19_GDC_Adjective_tweet",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Adjective-tweet/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_All_article_data_text",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/All-article-data-text/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_All_Frequent_term",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/All-Frequent-term/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_All_tag_tweet_text_data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/All-tag-tweet-text-data/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Article_Adjective",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Article-Adjective/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Article_Co_occurence",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Article-Co-occurence/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Article_data11",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Article-data11/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Article_ngram_co_occrence",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Article-ngram-co-occrence/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Article_Noun",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Article-Noun/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Article_Topic_model",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Article-Topic-model/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Article_verb",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Article-verb/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Article_word_cloud",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Article-word-cloud/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_cases_consolidated",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/cases-consolidated/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_case_fatality_rate",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/case-fatality-rate/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_city_population",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/city-population/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_classifier_feature_importances",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/classifier-feature-importances/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_classifier_metrics",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/classifier-metrics/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_classifier_predict_proba",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/classifier-predict-proba/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_clustered_geo",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/clustered-geo/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_confirmed_forecast",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/confirmed-forecast/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_country_area",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/country-area/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Co_occurence_tweet",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Co-occurence-tweet/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_csse_daily",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/csse-daily/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_csse_time_series",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/csse-time-series/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_csse_time_series_clean",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/csse-time-series-clean/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_csse_time_series_deaths",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/csse-time-series-deaths/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_csse_time_series_deaths_clean",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/csse-time-series-deaths-clean/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_csse_time_series_recoveries",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/csse-time-series-recoveries/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_csse_time_series_recoveries_cl",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/csse-time-series-recoveries-cl/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_csse_time_series_US",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/csse-time-series-US/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_csse_time_series_US_deaths",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/csse-time-series-US-deaths/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Data_hit",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Data-hit/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_deaths_forecast",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/deaths-forecast/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Emotion_sentiscore_tweet",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Emotion-sentiscore-tweet/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_FF_SRCI_covid_testing_stats",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/FF-SRCI-covid-testing-stats/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Kaggle_text_covid_19",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Kaggle-text-covid-19/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Kaggle_Text_data_covid_19",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Kaggle-Text-data-covid-19/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Kaggle_Text_data_covid_19_ERR",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Kaggle-Text-data-covid-19-ERR/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_ncov2019_small",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/ncov2019-small/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_ncov2019_small_clean",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/ncov2019-small-clean/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_ngram_co_occrence_tweet",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/ngram-co-occrence-tweet/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Noun_tweet",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Noun-tweet/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_ph_confirmed_cases",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/ph-confirmed-cases/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_ph_confirmed_cases_clean",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/ph-confirmed-cases-clean/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_ph_supplemental",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/ph-supplemental/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_population_by_age",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/population-by-age/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_recoveries_forecast",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/recoveries-forecast/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Sentiment__tweet_data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Sentiment--tweet-data/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_SIR_Predictions",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/SIR-Predictions/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Tweet_data_covid_19",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Tweet-data-covid-19/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Twitter_data",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Twitter-data/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Twitter_Sentiment_Score",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Twitter-Sentiment-Score/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_Twitter_sentiscore_tweet",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/Twitter-sentiscore-tweet/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_verb_tweet",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/verb-tweet/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_without_intervention",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/without-intervention/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_with_intervention",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/with-intervention/'));
create foreign table gs_tables_db."TRNG_COVID19_GDC_word_cloud_tweet",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-COVID19-GDC/word-cloud-tweet/'));
replace view TRNG_COVID19_GDC.Adjective_tweet as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Adjective_tweet";
replace view TRNG_COVID19_GDC.All_Frequent_term as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_All_Frequent_term";
replace view TRNG_COVID19_GDC.All_article_data_text as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_All_article_data_text";
replace view TRNG_COVID19_GDC.All_tag_tweet_text_data as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_All_tag_tweet_text_data";
replace view TRNG_COVID19_GDC.Article_Adjective as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Article_Adjective";
replace view TRNG_COVID19_GDC.Article_Co_occurence as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Article_Co_occurence";
replace view TRNG_COVID19_GDC.Article_Noun as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Article_Noun";
replace view TRNG_COVID19_GDC.Article_Topic_model as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Article_Topic_model";
replace view TRNG_COVID19_GDC.Article_data11 as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Article_data11";
replace view TRNG_COVID19_GDC.Article_ngram_co_occrence as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Article_ngram_co_occrence";
replace view TRNG_COVID19_GDC.Article_verb as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Article_verb";
replace view TRNG_COVID19_GDC.Article_word_cloud as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Article_word_cloud";
replace view TRNG_COVID19_GDC.Co_occurence_tweet as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Co_occurence_tweet";
replace view TRNG_COVID19_GDC.Data_hit as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Data_hit";
replace view TRNG_COVID19_GDC.Emotion_sentiscore_tweet as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Emotion_sentiscore_tweet";
replace view TRNG_COVID19_GDC.FF_SRCI_covid_testing_stats as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_FF_SRCI_covid_testing_stats";
replace view TRNG_COVID19_GDC.Kaggle_Text_data_covid_19 as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Kaggle_Text_data_covid_19";
replace view TRNG_COVID19_GDC.Kaggle_Text_data_covid_19_ERR as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Kaggle_Text_data_covid_19_ERR";
replace view TRNG_COVID19_GDC.Kaggle_text_covid_19 as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Kaggle_text_covid_19";
replace view TRNG_COVID19_GDC.Noun_tweet as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Noun_tweet";
replace view TRNG_COVID19_GDC.SIR_Predictions as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_SIR_Predictions";
replace view TRNG_COVID19_GDC.Sentiment__tweet_data as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Sentiment__tweet_data";
replace view TRNG_COVID19_GDC.Tweet_data_covid_19 as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Tweet_data_covid_19";
replace view TRNG_COVID19_GDC.Twitter_Sentiment_Score as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Twitter_Sentiment_Score";
replace view TRNG_COVID19_GDC.Twitter_data as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Twitter_data";
replace view TRNG_COVID19_GDC.Twitter_sentiscore_tweet as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_Twitter_sentiscore_tweet";
replace view TRNG_COVID19_GDC.case_fatality_rate as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_case_fatality_rate";
replace view TRNG_COVID19_GDC.cases_consolidated as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_cases_consolidated";
replace view TRNG_COVID19_GDC.city_population as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_city_population";
replace view TRNG_COVID19_GDC.classifier_feature_importances as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_classifier_feature_importances";
replace view TRNG_COVID19_GDC.classifier_metrics as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_classifier_metrics";
replace view TRNG_COVID19_GDC.classifier_predict_proba as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_classifier_predict_proba";
replace view TRNG_COVID19_GDC.clustered_geo as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_clustered_geo";
replace view TRNG_COVID19_GDC.confirmed_forecast as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_confirmed_forecast";
replace view TRNG_COVID19_GDC.country_area as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_country_area";
replace view TRNG_COVID19_GDC.csse_daily as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_csse_daily";
replace view TRNG_COVID19_GDC.csse_time_series as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_csse_time_series";
replace view TRNG_COVID19_GDC.csse_time_series_US as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_csse_time_series_US";
replace view TRNG_COVID19_GDC.csse_time_series_US_deaths as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_csse_time_series_US_deaths";
replace view TRNG_COVID19_GDC.csse_time_series_clean as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_csse_time_series_clean";
replace view TRNG_COVID19_GDC.csse_time_series_deaths as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_csse_time_series_deaths";
replace view TRNG_COVID19_GDC.csse_time_series_deaths_clean as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_csse_time_series_deaths_clean";
replace view TRNG_COVID19_GDC.csse_time_series_recoveries as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_csse_time_series_recoveries";
replace view TRNG_COVID19_GDC.csse_time_series_recoveries_cl as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_csse_time_series_recoveries_cl";
replace view TRNG_COVID19_GDC.deaths_forecast as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_deaths_forecast";
replace view TRNG_COVID19_GDC.ncov2019_small as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_ncov2019_small";
replace view TRNG_COVID19_GDC.ncov2019_small_clean as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_ncov2019_small_clean";
replace view TRNG_COVID19_GDC.ngram_co_occrence_tweet as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_ngram_co_occrence_tweet";
replace view TRNG_COVID19_GDC.ph_confirmed_cases as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_ph_confirmed_cases";
replace view TRNG_COVID19_GDC.ph_confirmed_cases_clean as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_ph_confirmed_cases_clean";
replace view TRNG_COVID19_GDC.ph_supplemental as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_ph_supplemental";
replace view TRNG_COVID19_GDC.population_by_age as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_population_by_age";
replace view TRNG_COVID19_GDC.recoveries_forecast as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_recoveries_forecast";
replace view TRNG_COVID19_GDC.verb_tweet as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_verb_tweet";
replace view TRNG_COVID19_GDC.with_intervention as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_with_intervention";
replace view TRNG_COVID19_GDC.without_intervention as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_without_intervention";
replace view TRNG_COVID19_GDC.word_cloud_tweet as locking row for access select * from  gs_tables_db."TRNG_COVID19_GDC_word_cloud_tweet";
