create database TRNG_SQLE_TEST from demonow as perm=0;
create foreign table gs_tables_db."TRNG_SQLE_TEST_BI_SLS_LINE_JCE_SPND",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/BI-SLS-LINE-JCE-SPND/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_decisiontree_predict",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/decisiontree-predict/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_decision_forest_predict_indb_u",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/decision-forest-predict-indb-u/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_decision_forest_predict_indb_u",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/decision-forest-predict-indb-u/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_decision_forest_predict_indb_u",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/decision-forest-predict-indb-u/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_decision_forest_predict_indb_u",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/decision-forest-predict-indb-u/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_decision_forest_predict_indb_u",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/decision-forest-predict-indb-u/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_glm_model",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/glm-model/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_glm_predict_indb_user_0",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/glm-predict-indb-user-0/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_glm_scale_stat",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/glm-scale-stat/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_glm_test_scaled",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/glm-test-scaled/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_imdb_reviews_model",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/imdb-reviews-model/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_imdb_reviews_train",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/imdb-reviews-train/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_LINE_ITEM_JUICE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/LINE-ITEM-JUICE/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_misspelled_words",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/misspelled-words/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_misspelled_words_processed",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/misspelled-words-processed/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_REVW",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/REVW/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_rf_model",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/rf-model/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_SLS_TRANS_LINE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/SLS-TRANS-LINE/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_sls_visit_web",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/sls-visit-web/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_sls_visit_web_full",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/sls-visit-web-full/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_sls_visit_web_time",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/sls-visit-web-time/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_suicide_risk_model",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/suicide-risk-model/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_suicide_risk_test",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/suicide-risk-test/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_test_features",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/test-features/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_test_raw",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/test-raw/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_text_tokenize_imdb_reviews",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/text-tokenize-imdb-reviews/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_train_features",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/train-features/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_train_raw",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/train-raw/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_visit_inpage_event",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/visit-inpage-event/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_visit_inpage_event_s",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/visit-inpage-event-s/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_visit_inpage_event_s_old",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/visit-inpage-event-s-old/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_visit_inpage_event_web_url",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/visit-inpage-event-web-url/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_VISIT_SLS_TRANS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/VISIT-SLS-TRANS/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_WEB_PAGE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/WEB-PAGE/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_wine_attribute_test",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/wine-attribute-test/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_wine_attribute_train",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/wine-attribute-train/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_wine_model",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/wine-model/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_wine_quality",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/wine-quality/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_wine_quality_svm_model",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/wine-quality-svm-model/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_wine_quality_test",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/wine-quality-test/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_wine_quality_unpivot",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/wine-quality-unpivot/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_wine_response_test",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/wine-response-test/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_wine_response_train",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/wine-response-train/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_wine_test_unpivot",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/wine-test-unpivot/'));
create foreign table gs_tables_db."TRNG_SQLE_TEST_wine_train_unpivot",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-SQLE-TEST/wine-train-unpivot/'));
replace view TRNG_SQLE_TEST.BI_SLS_LINE_JCE_SPND as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_BI_SLS_LINE_JCE_SPND";
replace view TRNG_SQLE_TEST.LINE_ITEM_JUICE as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_LINE_ITEM_JUICE";
replace view TRNG_SQLE_TEST.REVW as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_REVW";
replace view TRNG_SQLE_TEST.SLS_TRANS_LINE as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_SLS_TRANS_LINE";
replace view TRNG_SQLE_TEST.VISIT_SLS_TRANS as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_VISIT_SLS_TRANS";
replace view TRNG_SQLE_TEST.WEB_PAGE as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_WEB_PAGE";
replace view TRNG_SQLE_TEST.decision_forest_predict_indb_u as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_decision_forest_predict_indb_u";
replace view TRNG_SQLE_TEST.decision_forest_predict_indb_u as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_decision_forest_predict_indb_u";
replace view TRNG_SQLE_TEST.decision_forest_predict_indb_u as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_decision_forest_predict_indb_u";
replace view TRNG_SQLE_TEST.decision_forest_predict_indb_u as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_decision_forest_predict_indb_u";
replace view TRNG_SQLE_TEST.decision_forest_predict_indb_u as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_decision_forest_predict_indb_u";
replace view TRNG_SQLE_TEST.decisiontree_predict as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_decisiontree_predict";
replace view TRNG_SQLE_TEST.glm_model as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_glm_model";
replace view TRNG_SQLE_TEST.glm_predict_indb_user_0 as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_glm_predict_indb_user_0";
replace view TRNG_SQLE_TEST.glm_scale_stat as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_glm_scale_stat";
replace view TRNG_SQLE_TEST.glm_test_scaled as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_glm_test_scaled";
replace view TRNG_SQLE_TEST.imdb_reviews_model as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_imdb_reviews_model";
replace view TRNG_SQLE_TEST.imdb_reviews_train as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_imdb_reviews_train";
replace view TRNG_SQLE_TEST.misspelled_words as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_misspelled_words";
replace view TRNG_SQLE_TEST.misspelled_words_processed as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_misspelled_words_processed";
replace view TRNG_SQLE_TEST.rf_model as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_rf_model";
replace view TRNG_SQLE_TEST.sls_visit_web as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_sls_visit_web";
replace view TRNG_SQLE_TEST.sls_visit_web_full as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_sls_visit_web_full";
replace view TRNG_SQLE_TEST.sls_visit_web_time as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_sls_visit_web_time";
replace view TRNG_SQLE_TEST.suicide_risk_model as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_suicide_risk_model";
replace view TRNG_SQLE_TEST.suicide_risk_test as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_suicide_risk_test";
replace view TRNG_SQLE_TEST.test_features as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_test_features";
replace view TRNG_SQLE_TEST.test_raw as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_test_raw";
replace view TRNG_SQLE_TEST.text_tokenize_imdb_reviews as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_text_tokenize_imdb_reviews";
replace view TRNG_SQLE_TEST.train_features as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_train_features";
replace view TRNG_SQLE_TEST.train_raw as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_train_raw";
replace view TRNG_SQLE_TEST.visit_inpage_event as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_visit_inpage_event";
replace view TRNG_SQLE_TEST.visit_inpage_event_s as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_visit_inpage_event_s";
replace view TRNG_SQLE_TEST.visit_inpage_event_s_old as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_visit_inpage_event_s_old";
replace view TRNG_SQLE_TEST.visit_inpage_event_web_url as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_visit_inpage_event_web_url";
replace view TRNG_SQLE_TEST.wine_attribute_test as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_wine_attribute_test";
replace view TRNG_SQLE_TEST.wine_attribute_train as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_wine_attribute_train";
replace view TRNG_SQLE_TEST.wine_model as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_wine_model";
replace view TRNG_SQLE_TEST.wine_quality as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_wine_quality";
replace view TRNG_SQLE_TEST.wine_quality_svm_model as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_wine_quality_svm_model";
replace view TRNG_SQLE_TEST.wine_quality_test as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_wine_quality_test";
replace view TRNG_SQLE_TEST.wine_quality_unpivot as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_wine_quality_unpivot";
replace view TRNG_SQLE_TEST.wine_response_test as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_wine_response_test";
replace view TRNG_SQLE_TEST.wine_response_train as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_wine_response_train";
replace view TRNG_SQLE_TEST.wine_test_unpivot as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_wine_test_unpivot";
replace view TRNG_SQLE_TEST.wine_train_unpivot as locking row for access select * from  gs_tables_db."TRNG_SQLE_TEST_wine_train_unpivot";
