create database TRNG_GamingSessions from demonow as perm=0;
create foreign table gs_tables_db."TRNG_GamingSessions_customer_ip",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-GamingSessions/customer-ip/'));
create foreign table gs_tables_db."TRNG_GamingSessions_games",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-GamingSessions/games/'));
create foreign table gs_tables_db."TRNG_GamingSessions_game_affinity",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-GamingSessions/game-affinity/'));
create foreign table gs_tables_db."TRNG_GamingSessions_gaming_events",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-GamingSessions/gaming-events/'));
create foreign table gs_tables_db."TRNG_GamingSessions_gaming_events_sessions",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-GamingSessions/gaming-events-sessions/'));
create foreign table gs_tables_db."TRNG_GamingSessions_gaming_events_sessions_simil",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-GamingSessions/gaming-events-sessions-simil/'));
create foreign table gs_tables_db."TRNG_GamingSessions_gaming_events_sessions_similar",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-GamingSessions/gaming-events-sessions-similar/'));
create foreign table gs_tables_db."TRNG_GamingSessions_gaming_events_sessions_similar",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-GamingSessions/gaming-events-sessions-similar/'));
create foreign table gs_tables_db."TRNG_GamingSessions_gaming_events_sessions_simil_d",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-GamingSessions/gaming-events-sessions-simil-d/'));
create foreign table gs_tables_db."TRNG_GamingSessions_gaming_uniquesessionpaths",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-GamingSessions/gaming-uniquesessionpaths/'));
replace view TRNG_GamingSessions.customer_ip as locking row for access select * from  gs_tables_db."TRNG_GamingSessions_customer_ip";
replace view TRNG_GamingSessions.game_affinity as locking row for access select * from  gs_tables_db."TRNG_GamingSessions_game_affinity";
replace view TRNG_GamingSessions.games as locking row for access select * from  gs_tables_db."TRNG_GamingSessions_games";
replace view TRNG_GamingSessions.gaming_events as locking row for access select * from  gs_tables_db."TRNG_GamingSessions_gaming_events";
replace view TRNG_GamingSessions.gaming_events_sessions as locking row for access select * from  gs_tables_db."TRNG_GamingSessions_gaming_events_sessions";
replace view TRNG_GamingSessions.gaming_events_sessions_simil as locking row for access select * from  gs_tables_db."TRNG_GamingSessions_gaming_events_sessions_simil";
replace view TRNG_GamingSessions.gaming_events_sessions_simil_d as locking row for access select * from  gs_tables_db."TRNG_GamingSessions_gaming_events_sessions_simil_d";
replace view TRNG_GamingSessions.gaming_events_sessions_similar as locking row for access select * from  gs_tables_db."TRNG_GamingSessions_gaming_events_sessions_similar";
replace view TRNG_GamingSessions.gaming_events_sessions_similar as locking row for access select * from  gs_tables_db."TRNG_GamingSessions_gaming_events_sessions_similar";
replace view TRNG_GamingSessions.gaming_uniquesessionpaths as locking row for access select * from  gs_tables_db."TRNG_GamingSessions_gaming_uniquesessionpaths";
