create database TRNG_HEALTHCARE from demonow as perm=0;
create foreign table gs_tables_db."TRNG_HEALTHCARE_BENEFICIARY_SUMMARY",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/BENEFICIARY-SUMMARY/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_BENEFICIARY_SUMMARY_latest",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/BENEFICIARY-SUMMARY-latest/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_breast_cancer_mle_model",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/breast-cancer-mle-model/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_breast_cancer_mle_monitor",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/breast-cancer-mle-monitor/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_breast_cancer_test",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/breast-cancer-test/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_breast_cancer_train",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/breast-cancer-train/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_CARRIER_CLAIMS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/CARRIER-CLAIMS/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_CARRIER_CLAIMS_CUST",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/CARRIER-CLAIMS-CUST/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_CARRIER_CLAIMS_OLD",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/CARRIER-CLAIMS-OLD/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_CCS_DX",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/CCS-DX/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_CCS_PR",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/CCS-PR/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_COVID_19_cases_US",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/COVID-19-cases-US/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_COVID_19_cases_US_load",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/COVID-19-cases-US-load/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_COVID_19_pop",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/COVID-19-pop/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_COVID_19_US_State_pivot",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/COVID-19-US-State-pivot/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_cs_norms",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/cs-norms/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_DRG_CODES",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/DRG-CODES/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_facility_Correlation",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/facility-Correlation/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_facility_Correlation_State",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/facility-Correlation-State/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_facility_info",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/facility-info/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_Facility_Score",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/Facility-Score/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_GEORGIA_County_Score2",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/GEORGIA-County-Score2/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_GEORGIA_HEALTH_MEASURES",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/GEORGIA-HEALTH-MEASURES/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_HL7_MSG_HDR",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/HL7-MSG-HDR/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_hospital_beds_TS_order",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/hospital-beds-TS-order/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_Hospital_Readmissions",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/Hospital-Readmissions/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_ICD_ORDER",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/ICD-ORDER/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_INPATIENT_CLAIMS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/INPATIENT-CLAIMS/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_IPPS_Provider_Smry",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/IPPS-Provider-Smry/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_MI_HEALTH_MEASURES",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/MI-HEALTH-MEASURES/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_OUTPATIENT_CLAIMS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/OUTPATIENT-CLAIMS/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_patient_sel_cond",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/patient-sel-cond/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_patient_survey",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/patient-survey/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_PRESCRIPTION_DRUG_EVENTS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/PRESCRIPTION-DRUG-EVENTS/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_RJ_HEALTH_MEASURES",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/RJ-HEALTH-MEASURES/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_RXNSAT",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/RXNSAT/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_SSA_COUNTY_CD",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/SSA-COUNTY-CD/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_state_abbrv",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/state-abbrv/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_synthea_allergies_raw",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/synthea-allergies-raw/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_US_County_Score",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/US-County-Score/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_US_HOPITALS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/US-HOPITALS/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_US_Hospital_bed",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/US-Hospital-bed/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_US_Hospital_bed_fcst",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/US-Hospital-bed-fcst/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_US_Hospital_bed_model",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/US-Hospital-bed-model/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_US_Hospital_bed_res",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/US-Hospital-bed-res/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_US_NCASES_cluster",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/US-NCASES-cluster/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_US_NCASES_cluster_state",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/US-NCASES-cluster-state/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_US_Nursing_Facility",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/US-Nursing-Facility/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_va_conditions",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/va-conditions/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_va_encounters",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/va-encounters/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_va_medications",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/va-medications/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_va_observations",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/va-observations/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_va_observations_full",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/va-observations-full/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_va_patients",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/va-patients/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_va_procedures",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/va-procedures/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_va_providers",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/va-providers/'));
create foreign table gs_tables_db."TRNG_HEALTHCARE_zipcodes",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-HEALTHCARE/zipcodes/'));
replace view TRNG_HEALTHCARE.BENEFICIARY_SUMMARY as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_BENEFICIARY_SUMMARY";
replace view TRNG_HEALTHCARE.BENEFICIARY_SUMMARY_latest as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_BENEFICIARY_SUMMARY_latest";
replace view TRNG_HEALTHCARE.CARRIER_CLAIMS as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_CARRIER_CLAIMS";
replace view TRNG_HEALTHCARE.CARRIER_CLAIMS_CUST as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_CARRIER_CLAIMS_CUST";
replace view TRNG_HEALTHCARE.CARRIER_CLAIMS_OLD as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_CARRIER_CLAIMS_OLD";
replace view TRNG_HEALTHCARE.CCS_DX as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_CCS_DX";
replace view TRNG_HEALTHCARE.CCS_PR as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_CCS_PR";
replace view TRNG_HEALTHCARE.COVID_19_US_State_pivot as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_COVID_19_US_State_pivot";
replace view TRNG_HEALTHCARE.COVID_19_cases_US as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_COVID_19_cases_US";
replace view TRNG_HEALTHCARE.COVID_19_cases_US_load as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_COVID_19_cases_US_load";
replace view TRNG_HEALTHCARE.COVID_19_pop as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_COVID_19_pop";
replace view TRNG_HEALTHCARE.DRG_CODES as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_DRG_CODES";
replace view TRNG_HEALTHCARE.Facility_Score as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_Facility_Score";
replace view TRNG_HEALTHCARE.GEORGIA_County_Score2 as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_GEORGIA_County_Score2";
replace view TRNG_HEALTHCARE.GEORGIA_HEALTH_MEASURES as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_GEORGIA_HEALTH_MEASURES";
replace view TRNG_HEALTHCARE.HL7_MSG_HDR as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_HL7_MSG_HDR";
replace view TRNG_HEALTHCARE.Hospital_Readmissions as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_Hospital_Readmissions";
replace view TRNG_HEALTHCARE.ICD_ORDER as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_ICD_ORDER";
replace view TRNG_HEALTHCARE.INPATIENT_CLAIMS as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_INPATIENT_CLAIMS";
replace view TRNG_HEALTHCARE.IPPS_Provider_Smry as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_IPPS_Provider_Smry";
replace view TRNG_HEALTHCARE.MI_HEALTH_MEASURES as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_MI_HEALTH_MEASURES";
replace view TRNG_HEALTHCARE.OUTPATIENT_CLAIMS as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_OUTPATIENT_CLAIMS";
replace view TRNG_HEALTHCARE.PRESCRIPTION_DRUG_EVENTS as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_PRESCRIPTION_DRUG_EVENTS";
replace view TRNG_HEALTHCARE.RJ_HEALTH_MEASURES as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_RJ_HEALTH_MEASURES";
replace view TRNG_HEALTHCARE.RXNSAT as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_RXNSAT";
replace view TRNG_HEALTHCARE.SSA_COUNTY_CD as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_SSA_COUNTY_CD";
replace view TRNG_HEALTHCARE.US_County_Score as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_US_County_Score";
replace view TRNG_HEALTHCARE.US_HOPITALS as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_US_HOPITALS";
replace view TRNG_HEALTHCARE.US_Hospital_bed as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_US_Hospital_bed";
replace view TRNG_HEALTHCARE.US_Hospital_bed_fcst as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_US_Hospital_bed_fcst";
replace view TRNG_HEALTHCARE.US_Hospital_bed_model as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_US_Hospital_bed_model";
replace view TRNG_HEALTHCARE.US_Hospital_bed_res as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_US_Hospital_bed_res";
replace view TRNG_HEALTHCARE.US_NCASES_cluster as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_US_NCASES_cluster";
replace view TRNG_HEALTHCARE.US_NCASES_cluster_state as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_US_NCASES_cluster_state";
replace view TRNG_HEALTHCARE.US_Nursing_Facility as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_US_Nursing_Facility";
replace view TRNG_HEALTHCARE.breast_cancer_mle_model as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_breast_cancer_mle_model";
replace view TRNG_HEALTHCARE.breast_cancer_mle_monitor as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_breast_cancer_mle_monitor";
replace view TRNG_HEALTHCARE.breast_cancer_test as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_breast_cancer_test";
replace view TRNG_HEALTHCARE.breast_cancer_train as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_breast_cancer_train";
replace view TRNG_HEALTHCARE.cs_norms as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_cs_norms";
replace view TRNG_HEALTHCARE.facility_Correlation as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_facility_Correlation";
replace view TRNG_HEALTHCARE.facility_Correlation_State as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_facility_Correlation_State";
replace view TRNG_HEALTHCARE.facility_info as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_facility_info";
replace view TRNG_HEALTHCARE.hospital_beds_TS_order as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_hospital_beds_TS_order";
replace view TRNG_HEALTHCARE.patient_sel_cond as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_patient_sel_cond";
replace view TRNG_HEALTHCARE.patient_survey as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_patient_survey";
replace view TRNG_HEALTHCARE.state_abbrv as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_state_abbrv";
replace view TRNG_HEALTHCARE.synthea_allergies_raw as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_synthea_allergies_raw";
replace view TRNG_HEALTHCARE.va_conditions as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_va_conditions";
replace view TRNG_HEALTHCARE.va_encounters as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_va_encounters";
replace view TRNG_HEALTHCARE.va_medications as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_va_medications";
replace view TRNG_HEALTHCARE.va_observations as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_va_observations";
replace view TRNG_HEALTHCARE.va_observations_full as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_va_observations_full";
replace view TRNG_HEALTHCARE.va_patients as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_va_patients";
replace view TRNG_HEALTHCARE.va_procedures as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_va_procedures";
replace view TRNG_HEALTHCARE.va_providers as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_va_providers";
replace view TRNG_HEALTHCARE.zipcodes as locking row for access select * from  gs_tables_db."TRNG_HEALTHCARE_zipcodes";
