create database TRNG_OilGasDrilling from demonow as perm=0;
create foreign table gs_tables_db."TRNG_OilGasDrilling_DDaaS_Survey_Logs",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-OilGasDrilling/DDaaS-Survey-Logs/'));
create foreign table gs_tables_db."TRNG_OilGasDrilling_DDaaS_Survey_Logs_Stand_Test",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-OilGasDrilling/DDaaS-Survey-Logs-Stand-Test/'));
create foreign table gs_tables_db."TRNG_OilGasDrilling_Rig_State_Drilling_Stat",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-OilGasDrilling/Rig-State-Drilling-Stat/'));
create foreign table gs_tables_db."TRNG_OilGasDrilling_Rig_State_Drilling_Stat_orig",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-OilGasDrilling/Rig-State-Drilling-Stat-orig/'));
create foreign table gs_tables_db."TRNG_OilGasDrilling_Srfc_Sensor_Parms_PPI_Flat",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-OilGasDrilling/Srfc-Sensor-Parms-PPI-Flat/'));
create foreign table gs_tables_db."TRNG_OilGasDrilling_Srfc_Sensor_Parms_PPI_Flat_Rig",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-OilGasDrilling/Srfc-Sensor-Parms-PPI-Flat-Rig/'));
create foreign table gs_tables_db."TRNG_OilGasDrilling_Wells",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-OilGasDrilling/Wells/'));
create foreign table gs_tables_db."TRNG_OilGasDrilling_Well_Bores_TPL",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-OilGasDrilling/Well-Bores-TPL/'));
create foreign table gs_tables_db."TRNG_OilGasDrilling_Well_Rigs",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-OilGasDrilling/Well-Rigs/'));
replace view TRNG_OilGasDrilling.DDaaS_Survey_Logs as locking row for access select * from  gs_tables_db."TRNG_OilGasDrilling_DDaaS_Survey_Logs";
replace view TRNG_OilGasDrilling.DDaaS_Survey_Logs_Stand_Test as locking row for access select * from  gs_tables_db."TRNG_OilGasDrilling_DDaaS_Survey_Logs_Stand_Test";
replace view TRNG_OilGasDrilling.Rig_State_Drilling_Stat as locking row for access select * from  gs_tables_db."TRNG_OilGasDrilling_Rig_State_Drilling_Stat";
replace view TRNG_OilGasDrilling.Rig_State_Drilling_Stat_orig as locking row for access select * from  gs_tables_db."TRNG_OilGasDrilling_Rig_State_Drilling_Stat_orig";
replace view TRNG_OilGasDrilling.Srfc_Sensor_Parms_PPI_Flat as locking row for access select * from  gs_tables_db."TRNG_OilGasDrilling_Srfc_Sensor_Parms_PPI_Flat";
replace view TRNG_OilGasDrilling.Srfc_Sensor_Parms_PPI_Flat_Rig as locking row for access select * from  gs_tables_db."TRNG_OilGasDrilling_Srfc_Sensor_Parms_PPI_Flat_Rig";
replace view TRNG_OilGasDrilling.Well_Bores_TPL as locking row for access select * from  gs_tables_db."TRNG_OilGasDrilling_Well_Bores_TPL";
replace view TRNG_OilGasDrilling.Well_Rigs as locking row for access select * from  gs_tables_db."TRNG_OilGasDrilling_Well_Rigs";
replace view TRNG_OilGasDrilling.Wells as locking row for access select * from  gs_tables_db."TRNG_OilGasDrilling_Wells";
