create database TRNG_ColoradoCrimeDrug from demonow as perm=0;
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_BODY_ART_LICENSE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/BODY-ART-LICENSE/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_COUNTY",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/COUNTY/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_CRIME",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/CRIME/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_DRUG_CRIME",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/DRUG-CRIME/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_DUI_ARREST",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/DUI-ARREST/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_ELECTRICITY_REVENUE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/ELECTRICITY-REVENUE/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_EMPLOYMENT",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/EMPLOYMENT/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_FORECLOSURE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/FORECLOSURE/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_HEALTH_FACILITY",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/HEALTH-FACILITY/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_LIQUOR_LICENSE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/LIQUOR-LICENSE/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_MARIJUANA_BUSINESS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/MARIJUANA-BUSINESS/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_MARIJUANA_SALES_REVENUE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/MARIJUANA-SALES-REVENUE/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_MENTAL_DISTRESS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/MENTAL-DISTRESS/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_PERSONAL_INCOME",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/PERSONAL-INCOME/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_POPULATION",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/POPULATION/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_SCHOOL",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/SCHOOL/'));
create foreign table gs_tables_db."TRNG_ColoradoCrimeDrug_SEIZED_DRUGS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-ColoradoCrimeDrug/SEIZED-DRUGS/'));
replace view TRNG_ColoradoCrimeDrug.BODY_ART_LICENSE as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_BODY_ART_LICENSE";
replace view TRNG_ColoradoCrimeDrug.COUNTY as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_COUNTY";
replace view TRNG_ColoradoCrimeDrug.CRIME as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_CRIME";
replace view TRNG_ColoradoCrimeDrug.DRUG_CRIME as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_DRUG_CRIME";
replace view TRNG_ColoradoCrimeDrug.DUI_ARREST as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_DUI_ARREST";
replace view TRNG_ColoradoCrimeDrug.ELECTRICITY_REVENUE as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_ELECTRICITY_REVENUE";
replace view TRNG_ColoradoCrimeDrug.EMPLOYMENT as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_EMPLOYMENT";
replace view TRNG_ColoradoCrimeDrug.FORECLOSURE as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_FORECLOSURE";
replace view TRNG_ColoradoCrimeDrug.HEALTH_FACILITY as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_HEALTH_FACILITY";
replace view TRNG_ColoradoCrimeDrug.LIQUOR_LICENSE as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_LIQUOR_LICENSE";
replace view TRNG_ColoradoCrimeDrug.MARIJUANA_BUSINESS as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_MARIJUANA_BUSINESS";
replace view TRNG_ColoradoCrimeDrug.MARIJUANA_SALES_REVENUE as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_MARIJUANA_SALES_REVENUE";
replace view TRNG_ColoradoCrimeDrug.MENTAL_DISTRESS as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_MENTAL_DISTRESS";
replace view TRNG_ColoradoCrimeDrug.PERSONAL_INCOME as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_PERSONAL_INCOME";
replace view TRNG_ColoradoCrimeDrug.POPULATION as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_POPULATION";
replace view TRNG_ColoradoCrimeDrug.SCHOOL as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_SCHOOL";
replace view TRNG_ColoradoCrimeDrug.SEIZED_DRUGS as locking row for access select * from  gs_tables_db."TRNG_ColoradoCrimeDrug_SEIZED_DRUGS";
