create database TRNG_DataScienceExploration from demonow as perm=0;
create foreign table gs_tables_db."TRNG_DataScienceExploration_HOUSE_PRICES",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-DataScienceExploration/HOUSE-PRICES/'));
create foreign table gs_tables_db."TRNG_DataScienceExploration_MOVIE_LENS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-DataScienceExploration/MOVIE-LENS/'));
create foreign table gs_tables_db."TRNG_DataScienceExploration_MOVIE_LENS_MOVIES",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-DataScienceExploration/MOVIE-LENS-MOVIES/'));
create foreign table gs_tables_db."TRNG_DataScienceExploration_MOVIE_LENS_MOVIES_stg",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-DataScienceExploration/MOVIE-LENS-MOVIES-stg/'));
create foreign table gs_tables_db."TRNG_DataScienceExploration_MOVIE_LENS_USERS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-DataScienceExploration/MOVIE-LENS-USERS/'));
create foreign table gs_tables_db."TRNG_DataScienceExploration_ROSSMANN_SALES",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-DataScienceExploration/ROSSMANN-SALES/'));
create foreign table gs_tables_db."TRNG_DataScienceExploration_ROSSMANN_SALES_STG",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-DataScienceExploration/ROSSMANN-SALES-STG/'));
create foreign table gs_tables_db."TRNG_DataScienceExploration_ROSSMANN_SALES_STORE",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-DataScienceExploration/ROSSMANN-SALES-STORE/'));
create foreign table gs_tables_db."TRNG_DataScienceExploration_TELCO_CUSTOMERS",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-DataScienceExploration/TELCO-CUSTOMERS/'));
create foreign table gs_tables_db."TRNG_DataScienceExploration_TITANIC_TEST",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-DataScienceExploration/TITANIC-TEST/'));
create foreign table gs_tables_db."TRNG_DataScienceExploration_TITANIC_TRAIN",  external security gs_tables_db.auth using (location('/gs/storage.googleapis.com/demonow_development/TRNG-DataScienceExploration/TITANIC-TRAIN/'));
replace view TRNG_DataScienceExploration.HOUSE_PRICES as locking row for access select * from  gs_tables_db."TRNG_DataScienceExploration_HOUSE_PRICES";
replace view TRNG_DataScienceExploration.MOVIE_LENS as locking row for access select * from  gs_tables_db."TRNG_DataScienceExploration_MOVIE_LENS";
replace view TRNG_DataScienceExploration.MOVIE_LENS_MOVIES as locking row for access select * from  gs_tables_db."TRNG_DataScienceExploration_MOVIE_LENS_MOVIES";
replace view TRNG_DataScienceExploration.MOVIE_LENS_MOVIES_stg as locking row for access select * from  gs_tables_db."TRNG_DataScienceExploration_MOVIE_LENS_MOVIES_stg";
replace view TRNG_DataScienceExploration.MOVIE_LENS_USERS as locking row for access select * from  gs_tables_db."TRNG_DataScienceExploration_MOVIE_LENS_USERS";
replace view TRNG_DataScienceExploration.ROSSMANN_SALES as locking row for access select * from  gs_tables_db."TRNG_DataScienceExploration_ROSSMANN_SALES";
replace view TRNG_DataScienceExploration.ROSSMANN_SALES_STG as locking row for access select * from  gs_tables_db."TRNG_DataScienceExploration_ROSSMANN_SALES_STG";
replace view TRNG_DataScienceExploration.ROSSMANN_SALES_STORE as locking row for access select * from  gs_tables_db."TRNG_DataScienceExploration_ROSSMANN_SALES_STORE";
replace view TRNG_DataScienceExploration.TELCO_CUSTOMERS as locking row for access select * from  gs_tables_db."TRNG_DataScienceExploration_TELCO_CUSTOMERS";
replace view TRNG_DataScienceExploration.TITANIC_TEST as locking row for access select * from  gs_tables_db."TRNG_DataScienceExploration_TITANIC_TEST";
replace view TRNG_DataScienceExploration.TITANIC_TRAIN as locking row for access select * from  gs_tables_db."TRNG_DataScienceExploration_TITANIC_TRAIN";
